import type { Lesson } from './lessons'

export const lessons47to90: Record<number, Lesson> = {
  // ===== REPORTED SPEECH & QUESTIONS (Units 47-52) =====
  47: {
    rule: 'In reported speech, we move tenses "back" — present → past, past → past perfect, will → would. Pronouns and time words also change.',
    formula: 'He said (that) + tense shift back',
    examples: [
      { sentence: '"I\'m tired." → He said he was tired.', correct: true },
      { sentence: '"I\'ll call you." → She said she would call me.', correct: true },
      { sentence: '"I can swim." → He said he could swim.', correct: true },
      { sentence: '"I\'ve finished." → She said she had finished.', correct: true },
      { sentence: 'He said me that he was tired.', correct: false },
      { sentence: 'He told me that he was tired.', correct: true },
    ],
    notes: [
      '"Say" doesn\'t take an indirect object: "He said that…" (NOT "He said me").',
      '"Tell" needs an object: "He told me that…" (NOT "He told that…").',
      'If the information is still true, tense shift is optional: "He said he is/was a doctor."',
    ],
  },
  48: {
    rule: 'Reported questions: word order changes to statement order (no inversion). Use "if/whether" for yes/no questions.',
    formula: 'She asked + if/whether + subject + verb | She asked + wh-word + subject + verb',
    examples: [
      { sentence: '"Where do you live?" → She asked me where I lived.', correct: true },
      { sentence: '"Are you married?" → He asked me if I was married.', correct: true },
      { sentence: '"Can you help me?" → She asked whether I could help her.', correct: true },
      { sentence: 'He asked me where did I live.', correct: false },
      { sentence: 'He asked me where I lived.', correct: true },
      { sentence: '"What time is it?" → I asked what time it was.', correct: true },
    ],
    notes: [
      'No question mark in reported questions: "She asked where I lived." (not "lived?")',
      'No auxiliary "do/did" in reported questions: "He asked what I meant" (NOT "what did I mean").',
    ],
  },
  49: {
    rule: 'Question formation: auxiliary (do/does/did/is/are/have/can/will) + subject + verb. Wh-questions add the question word at the start.',
    formula: 'Wh- + auxiliary + subject + verb? | Auxiliary + subject + verb?',
    examples: [
      { sentence: 'Where does she work?', correct: true },
      { sentence: 'Where she works?', correct: false },
      { sentence: 'Have you ever been to Japan?', correct: true },
      { sentence: 'Who wants some coffee? (= who is the subject)', correct: true },
      { sentence: 'Who did you invite to the party? (= who is the object)', correct: true },
      { sentence: 'What happened? (= what is the subject → no auxiliary needed)', correct: true },
    ],
    notes: [
      'When "who/what/which" is the SUBJECT, don\'t use do/does/did: "Who wants…?" (NOT "Who does want?")',
      'When "who/what/which" is the OBJECT, use do/does/did: "Who did you meet?"',
    ],
  },
  50: {
    rule: 'Indirect questions with "Do you know …?", "Could you tell me …?", "I wonder …" — use statement word order, NOT question word order.',
    formula: 'Do you know + wh-word + subject + verb (NOT auxiliary + subject)',
    examples: [
      { sentence: 'Do you know where Tom is?', correct: true },
      { sentence: 'Do you know where is Tom?', correct: false },
      { sentence: 'Could you tell me what time the bank opens?', correct: true },
      { sentence: 'I wonder why she didn\'t come.', correct: true },
      { sentence: 'Do you know if/whether they\'re married?', correct: true },
      { sentence: 'I don\'t know what to do. (= what I should do)', correct: true },
    ],
  },
  51: {
    rule: 'Auxiliary verbs (have/do/can/will etc.) can be used alone to avoid repeating the main verb. "So do I" / "Neither do I" for agreement.',
    formula: 'So + auxiliary + subject (agreement +) | Neither + auxiliary + subject (agreement −)',
    examples: [
      { sentence: '"I\'m tired." — "So am I." (= me too)', correct: true },
      { sentence: '"I don\'t like spiders." — "Neither do I."', correct: true },
      { sentence: '"She can speak French." — "So can he."', correct: true },
      { sentence: '"Have you finished?" — "Yes, I have."', correct: true },
      { sentence: '"I think so." / "I hope so." / "I\'m afraid not."', correct: true },
      { sentence: '"Will it rain?" — "I don\'t think so."', correct: true },
    ],
  },
  52: {
    rule: 'Question tags are mini-questions at the end of a sentence. Positive sentence → negative tag. Negative sentence → positive tag.',
    formula: 'Positive sentence + negative tag? | Negative sentence + positive tag?',
    examples: [
      { sentence: 'You\'re from Poland, aren\'t you?', correct: true },
      { sentence: 'She doesn\'t speak French, does she?', correct: true },
      { sentence: 'It was a good film, wasn\'t it?', correct: true },
      { sentence: 'You haven\'t seen my keys, have you?', correct: true },
      { sentence: 'Let\'s go out, shall we?', correct: true },
      { sentence: 'Don\'t forget, will you?', correct: true },
    ],
    notes: [
      'After "I am", the tag is "aren\'t I?": "I\'m late, aren\'t I?"',
      'After "Let\'s", use "shall we?". After imperative, use "will you?"',
    ],
  },

  // ===== VERB PATTERNS: -ING AND TO (Units 53-66) =====
  53: {
    rule: 'Some verbs are followed by -ing (gerund): enjoy, mind, stop, finish, suggest, imagine, avoid, keep, consider, admit, deny, risk, practise, fancy.',
    formula: 'verb + -ing',
    examples: [
      { sentence: 'I enjoy reading books.', correct: true },
      { sentence: 'I enjoy to read books.', correct: false },
      { sentence: 'Have you finished eating?', correct: true },
      { sentence: 'She suggested going to a restaurant.', correct: true },
      { sentence: 'I can\'t imagine living in a cold country.', correct: true },
      { sentence: 'He denied stealing the money.', correct: true },
    ],
    notes: [
      'After "stop": "stop doing" = quit. "Stop to do" = pause in order to do something else.',
      '"I stopped smoking" ≠ "I stopped to smoke".',
    ],
  },
  54: {
    rule: 'Some verbs are followed by to + infinitive: decide, want, hope, expect, offer, promise, agree, refuse, learn, manage, afford, plan, arrange, fail, tend, pretend.',
    formula: 'verb + to + infinitive',
    examples: [
      { sentence: 'I decided to leave early.', correct: true },
      { sentence: 'She wants to buy a new car.', correct: true },
      { sentence: 'They agreed to help us.', correct: true },
      { sentence: 'I can\'t afford to go on holiday.', correct: true },
      { sentence: 'He promised to call me.', correct: true },
      { sentence: 'I hope to see you again soon.', correct: true },
    ],
  },
  55: {
    rule: 'Some verbs take object + to infinitive: want sb to do, ask sb to do, tell sb to do, advise sb to do, expect sb to do, persuade sb to do.',
    formula: 'verb + object + to + infinitive',
    examples: [
      { sentence: 'I want you to be happy.', correct: true },
      { sentence: 'She asked me to help her.', correct: true },
      { sentence: 'He told me to wait outside.', correct: true },
      { sentence: 'I want that you help me.', correct: false },
      { sentence: 'I want you to help me.', correct: true },
      { sentence: 'They advised us to book early.', correct: true },
    ],
  },
  56: {
    rule: 'Some verbs can be followed by -ing OR to-infinitive with a change in meaning: remember, forget, try, stop, regret, go on.',
    formula: 'remember/forget + -ing (= past) | remember/forget + to (= future action)',
    examples: [
      { sentence: 'I remember locking the door. (= I locked it, I remember this)', correct: true },
      { sentence: 'Remember to lock the door. (= don\'t forget to do it)', correct: true },
      { sentence: 'Try pressing the button. (= experiment)', correct: true },
      { sentence: 'I\'m trying to open the window. (= attempting)', correct: true },
      { sentence: 'He stopped smoking. (= quit the habit)', correct: true },
      { sentence: 'He stopped to smoke. (= paused to have a cigarette)', correct: true },
    ],
  },
  57: {
    rule: '"Try doing" = experiment. "Try to do" = attempt (difficult). "Need doing" = needs to be done (passive meaning). "Help (to) do" — "to" is optional.',
    formula: 'try + -ing (experiment) | try + to (attempt) | need + -ing (passive)',
    examples: [
      { sentence: 'Try turning the key the other way. (= maybe it will work)', correct: true },
      { sentence: 'I\'m trying to find a job. (= it\'s difficult)', correct: true },
      { sentence: 'The grass needs cutting. (= needs to be cut)', correct: true },
      { sentence: 'Can you help me (to) move this table?', correct: true },
      { sentence: 'My phone needs repairing.', correct: true },
      { sentence: 'I need to repair my phone.', correct: true },
    ],
  },
  58: {
    rule: 'Preposition + -ing: after prepositions (in, at, for, about, of, without, before, after), always use -ing form.',
    formula: 'preposition + verb-ing',
    examples: [
      { sentence: 'I\'m interested in learning languages.', correct: true },
      { sentence: 'She left without saying goodbye.', correct: true },
      { sentence: 'I\'m thinking about changing my job.', correct: true },
      { sentence: 'Thank you for helping me.', correct: true },
      { sentence: 'Instead of taking a taxi, we walked.', correct: true },
      { sentence: 'Are you good at cooking?', correct: true },
    ],
    notes: [
      'After "to" as a preposition: "I\'m looking forward to seeing you" (NOT "to see").',
      '"Used to doing" and "looking forward to doing" — here "to" is a preposition.',
    ],
  },
  59: {
    rule: '"Be/get used to doing" = be/become accustomed to. Don\'t confuse with "used to do" (past habit).',
    formula: 'be/get used to + -ing (= accustomed) | used to + base verb (= past habit)',
    examples: [
      { sentence: 'I\'m used to getting up early. (= I\'m accustomed to it)', correct: true },
      { sentence: 'I used to get up early. (= past habit, not anymore)', correct: true },
      { sentence: 'She\'s getting used to her new job.', correct: true },
      { sentence: 'He\'s not used to driving on the left.', correct: true },
      { sentence: 'I\'m used to live alone.', correct: false },
      { sentence: 'I\'m used to living alone.', correct: true },
    ],
  },
  60: {
    rule: 'Verbs of perception (see, hear, watch, notice, feel) + object + -ing (action in progress) or base verb (complete action).',
    formula: 'see/hear + object + -ing (in progress) | see/hear + object + base verb (complete)',
    examples: [
      { sentence: 'I saw her crossing the road. (= in the middle of crossing)', correct: true },
      { sentence: 'I saw her cross the road. (= from start to finish)', correct: true },
      { sentence: 'I heard someone singing.', correct: true },
      { sentence: 'I could feel my heart beating fast.', correct: true },
      { sentence: 'Did you notice anyone leave the building?', correct: true },
      { sentence: 'I watched them playing in the garden.', correct: true },
    ],
  },

  // ===== ARTICLES & COUNTABLE/UNCOUNTABLE (Units 61-80) =====
  61: {
    rule: 'Countable nouns can be singular or plural (a book / books). Uncountable nouns are always singular (water, information, advice, furniture, weather, news).',
    formula: 'Countable: a/an + singular, some + plural | Uncountable: some + noun (no "a")',
    examples: [
      { sentence: 'Can I have a piece of advice? (NOT "an advice")', correct: true },
      { sentence: 'The news is good. (NOT "are")', correct: true },
      { sentence: 'I need some information.', correct: true },
      { sentence: 'We need to buy some furniture.', correct: true },
      { sentence: 'I bought some new furnitures.', correct: false },
      { sentence: 'I bought some new furniture.', correct: true },
    ],
    notes: [
      'Common uncountable nouns: advice, information, news, furniture, luggage, weather, work, money, bread, rice, traffic, accommodation, behaviour, damage, luck, permission, progress, scenery, travel.',
      'To count uncountable nouns: a piece of advice, a loaf of bread, a glass of water.',
    ],
  },
  62: {
    rule: '"A/an" = one of many (not specific). "The" = a specific one (we know which one). No article = general.',
    formula: 'a/an (first mention, any) | the (specific, known) | ∅ (general plural/uncountable)',
    examples: [
      { sentence: 'I saw a dog in the park. The dog was very friendly.', correct: true },
      { sentence: 'Can you pass me the salt? (= we both know which salt)', correct: true },
      { sentence: 'I love music. (= music in general, no article)', correct: true },
      { sentence: 'The music at the party was too loud. (= specific music)', correct: true },
      { sentence: 'She\'s a teacher. (= one of many teachers)', correct: true },
      { sentence: 'The sun rises in the east.', correct: true },
    ],
    notes: [
      '"A" before consonant sounds. "An" before vowel sounds: an hour, a university.',
      'Use "the" with: superlatives (the best), ordinals (the first), only one (the sun, the moon).',
    ],
  },
  63: {
    rule: 'Don\'t use "the" with general plural or uncountable nouns, names of countries (most), cities, streets, languages, meals, or sports.',
    formula: 'No "the" with: general nouns, most countries, cities, meals, sports',
    examples: [
      { sentence: 'I like the music. (= wrong if meaning music in general)', correct: false },
      { sentence: 'I like music. (= in general)', correct: true },
      { sentence: 'She lives in France. (NOT "the France")', correct: true },
      { sentence: 'I had breakfast at 8. (NOT "the breakfast")', correct: true },
      { sentence: 'He plays football. (NOT "the football")', correct: true },
      { sentence: 'The Netherlands is in Europe. (= exception — "the" with some countries)', correct: true },
    ],
    notes: [
      '"The" with: the USA, the UK, the Netherlands, the Philippines (plurals or "united/republic/kingdom").',
      '"The" with: the Alps, the Atlantic, the Sahara, the Amazon (mountain ranges, oceans, deserts, rivers).',
    ],
  },
  64: {
    rule: 'Use "the" or no article with institutions (school, hospital, prison, church) depending on whether you mean the purpose or the building.',
    formula: 'Purpose (why it exists) → no article | Physical building → the',
    examples: [
      { sentence: 'She goes to school every day. (= she\'s a student)', correct: true },
      { sentence: 'I went to the school to talk to her teacher. (= the building)', correct: true },
      { sentence: 'He\'s in hospital. (= he\'s a patient)', correct: true },
      { sentence: 'I went to the hospital to visit him. (= the building)', correct: true },
      { sentence: 'She\'s in prison for robbery. (= she\'s a prisoner)', correct: true },
      { sentence: 'Go to bed! It\'s late. (= to sleep)', correct: true },
    ],
  },
  65: {
    rule: '"Some" in positive sentences, "any" in negatives and questions. But "some" in questions when offering or requesting.',
    formula: 'Positive → some | Negative/question → any | Offer/request → some',
    examples: [
      { sentence: 'I bought some bananas.', correct: true },
      { sentence: 'I didn\'t buy any bananas.', correct: true },
      { sentence: 'Have you got any money?', correct: true },
      { sentence: 'Would you like some coffee? (= offering)', correct: true },
      { sentence: 'Can I have some water, please? (= requesting)', correct: true },
      { sentence: 'You can sit anywhere you like. (= it doesn\'t matter where)', correct: true },
    ],
    notes: [
      '"Any" in positives means "it doesn\'t matter which": "You can come any time."',
      'Compounds: someone/anyone, something/anything, somewhere/anywhere.',
    ],
  },
  66: {
    rule: '"No/none/any" — "no" + noun, "none" alone or "none of". "No" is stronger than "not any".',
    formula: 'no + noun | none (alone) | none of + the/these/my',
    examples: [
      { sentence: 'There are no shops near here. (= not any shops)', correct: true },
      { sentence: '"How much money have you got?" "None." (= zero)', correct: true },
      { sentence: 'None of the students passed the exam.', correct: true },
      { sentence: 'I have no idea what to do.', correct: true },
      { sentence: 'None of us were hungry.', correct: true },
      { sentence: 'There\'s nothing to eat. (= no things)', correct: true },
    ],
  },
  67: {
    rule: '"Much" and "many" in negatives and questions. "A lot of" in all types. "Much/many" with "too" and "so" in positives.',
    formula: 'much + uncountable | many + countable plural | a lot of + both',
    examples: [
      { sentence: 'I don\'t have much time.', correct: true },
      { sentence: 'Do you have many friends here?', correct: true },
      { sentence: 'She has a lot of experience.', correct: true },
      { sentence: 'There are too many cars on the road.', correct: true },
      { sentence: 'I\'ve got much money.', correct: false },
      { sentence: 'I\'ve got a lot of money.', correct: true },
    ],
    notes: [
      '"Much" alone in positive sentences sounds formal. Prefer "a lot of".',
      '"How much?" (uncountable) / "How many?" (countable).',
    ],
  },
  68: {
    rule: '"(A) few" with countable nouns, "(a) little" with uncountable. "A few / a little" = some (positive). "Few / little" = not much/many (negative).',
    formula: 'a few + countable (= some) | a little + uncountable (= some) | few/little = not enough',
    examples: [
      { sentence: 'I have a few friends in London. (= some, enough)', correct: true },
      { sentence: 'I have few friends in London. (= not many, I\'m lonely)', correct: true },
      { sentence: 'We have a little time before the train. (= some, enough)', correct: true },
      { sentence: 'We have little time. Hurry up! (= not much)', correct: true },
      { sentence: 'Could I have a little milk in my coffee?', correct: true },
      { sentence: 'Very few people came to the meeting.', correct: true },
    ],
  },
  69: {
    rule: '"All", "every", "each", "whole" — ways to talk about totality. "All" + plural/uncountable. "Every/each" + singular.',
    formula: 'all + plural noun | every/each + singular noun | the whole + singular noun',
    examples: [
      { sentence: 'All children need love. (= children in general)', correct: true },
      { sentence: 'Every child needs love. (= each one)', correct: true },
      { sentence: 'Each room has a bathroom.', correct: true },
      { sentence: 'I\'ve read the whole book. (= from start to finish)', correct: true },
      { sentence: 'All of the students passed.', correct: true },
      { sentence: 'Every students need love.', correct: false },
    ],
  },
  70: {
    rule: '"Both" = two things. "Either" = one or the other. "Neither" = not one, not the other.',
    formula: 'both + plural | either/neither + singular | both … and | either … or | neither … nor',
    examples: [
      { sentence: 'Both restaurants are good.', correct: true },
      { sentence: 'You can have either tea or coffee.', correct: true },
      { sentence: 'Neither answer is correct.', correct: true },
      { sentence: 'I like both cats and dogs.', correct: true },
      { sentence: 'She speaks neither French nor German.', correct: true },
      { sentence: 'Either day is fine — Monday or Tuesday.', correct: true },
    ],
  },

  // ===== RELATIVE CLAUSES (Units 71-77) =====
  71: {
    rule: 'Relative clauses give extra information about a noun. "Who" for people, "which" for things, "that" for both, "where" for places, "whose" for possession.',
    formula: 'noun + who/which/that + verb',
    examples: [
      { sentence: 'The woman who lives next door is a doctor.', correct: true },
      { sentence: 'I bought a car which/that was very cheap.', correct: true },
      { sentence: 'The hotel where we stayed was very nice.', correct: true },
      { sentence: 'That\'s the man whose car was stolen.', correct: true },
      { sentence: 'The book that I\'m reading is really good.', correct: true },
      { sentence: 'Do you know anyone who can help me?', correct: true },
    ],
  },
  72: {
    rule: 'In defining relative clauses, when who/which/that is the OBJECT, it can be omitted. When it\'s the SUBJECT, it cannot.',
    formula: 'Subject → who/which required | Object → who/which can be dropped',
    examples: [
      { sentence: 'The film (that) we saw was excellent. (= "that" optional, it\'s the object)', correct: true },
      { sentence: 'The man who called you is here. (= "who" required, it\'s the subject)', correct: true },
      { sentence: 'Is there anything (that) I can do?', correct: true },
      { sentence: 'The people we met were very friendly. (= "who" dropped)', correct: true },
      { sentence: 'Everything (that) she said was true.', correct: true },
      { sentence: 'The man called you is here.', correct: false },
    ],
  },
  73: {
    rule: 'Prepositions in relative clauses can go at the end (informal) or before the relative pronoun (formal). "Whom" is used in formal English after prepositions.',
    formula: 'Informal: … who/that … preposition | Formal: preposition + whom/which',
    examples: [
      { sentence: 'The person (who) I spoke to was very helpful. (= informal)', correct: true },
      { sentence: 'The person to whom I spoke was very helpful. (= formal)', correct: true },
      { sentence: 'The hotel (which/that) we stayed at was nice.', correct: true },
      { sentence: 'The hotel at which we stayed was nice. (= formal)', correct: true },
      { sentence: 'What\'s the music (that) you\'re listening to?', correct: true },
      { sentence: 'She\'s the person (who) I was talking about.', correct: true },
    ],
  },
  74: {
    rule: 'Non-defining relative clauses add EXTRA information (not essential). They use commas and cannot use "that".',
    formula: 'Noun , who/which + clause , (extra info, commas, NO "that")',
    examples: [
      { sentence: 'My brother, who lives in London, is a doctor. (= extra info)', correct: true },
      { sentence: 'The book, which was published in 2020, is a bestseller.', correct: true },
      { sentence: 'My brother, that lives in London, is a doctor.', correct: false },
      { sentence: 'Paris, which is the capital of France, is beautiful.', correct: true },
      { sentence: 'Tom, whose wife is a lawyer, works at Google.', correct: true },
      { sentence: 'We went to the beach, where we had a picnic.', correct: true },
    ],
    notes: [
      'Defining (no commas): "The woman who lives next door…" (= which woman? — essential).',
      'Non-defining (commas): "My mother, who is 60,…" (= extra info — we know who).',
    ],
  },
  75: {
    rule: '"What" = "the thing(s) that". Don\'t confuse "what" (no noun before) with "which/that" (noun before).',
    formula: 'what = the thing(s) that (no noun before it)',
    examples: [
      { sentence: 'What happened was unexpected. (= the thing that happened)', correct: true },
      { sentence: 'I didn\'t hear what you said.', correct: true },
      { sentence: 'That\'s exactly what I wanted.', correct: true },
      { sentence: 'The thing what I need is more time.', correct: false },
      { sentence: 'The thing (that) I need is more time.', correct: true },
      { sentence: 'What I like about you is your honesty.', correct: true },
    ],
  },

  // ===== ADJECTIVES & ADVERBS (Units 76-82) =====
  76: {
    rule: 'Adjectives describe nouns. Adverbs describe verbs, adjectives, and other adverbs. Most adverbs are formed by adding -ly.',
    formula: 'adjective + noun | verb + adverb | adjective → adjective + ly = adverb',
    examples: [
      { sentence: 'She\'s a careful driver. She drives carefully.', correct: true },
      { sentence: 'The music is too loud. Please turn it down.', correct: true },
      { sentence: 'He speaks English very well. (NOT "very good")', correct: true },
      { sentence: 'She plays the piano good.', correct: false },
      { sentence: 'She plays the piano well.', correct: true },
      { sentence: 'It was a terribly cold day.', correct: true },
    ],
    notes: [
      'Irregular: good → well, fast → fast, hard → hard, late → late, early → early.',
      '"Hard" and "hardly" are different! "He works hard" ≠ "He hardly works" (= almost not).',
    ],
  },
  77: {
    rule: 'Comparatives (-er / more) for comparing two things. Superlatives (-est / most) for the top of a group.',
    formula: 'Short: -er / -est | Long: more / most | Irregular: good → better → best',
    examples: [
      { sentence: 'She\'s taller than her sister.', correct: true },
      { sentence: 'This is the most expensive restaurant in town.', correct: true },
      { sentence: 'My English is getting better.', correct: true },
      { sentence: 'This hotel is more comfortable than the other one.', correct: true },
      { sentence: 'It\'s the worst film I\'ve ever seen.', correct: true },
      { sentence: 'She\'s more tall than me.', correct: false },
    ],
    notes: [
      'Short adjectives (1 syllable): cheap → cheaper → cheapest.',
      'Long adjectives (2+ syllables): expensive → more expensive → most expensive.',
      'Irregular: good → better → best. bad → worse → worst. far → further/farther → furthest/farthest.',
    ],
  },
  78: {
    rule: '"As … as" for saying things are equal. "Not as … as" for saying they\'re different.',
    formula: 'as + adjective/adverb + as | not as/so + adjective + as',
    examples: [
      { sentence: 'Tom is as tall as his brother.', correct: true },
      { sentence: 'The exam wasn\'t as difficult as I expected.', correct: true },
      { sentence: 'I don\'t earn as much money as you.', correct: true },
      { sentence: 'She speaks English as well as a native speaker.', correct: true },
      { sentence: 'It\'s not as warm today as yesterday.', correct: true },
      { sentence: 'He runs twice as fast as me.', correct: true },
    ],
  },
  79: {
    rule: '"Enough" comes AFTER adjectives/adverbs but BEFORE nouns. "Too" = more than necessary (negative). "Enough" = sufficient.',
    formula: 'adjective + enough | too + adjective | enough + noun',
    examples: [
      { sentence: 'The coffee isn\'t hot enough. (adjective + enough)', correct: true },
      { sentence: 'I don\'t have enough money. (enough + noun)', correct: true },
      { sentence: 'It\'s too cold to go out.', correct: true },
      { sentence: 'She\'s old enough to drive.', correct: true },
      { sentence: 'I haven\'t got enough hot coffee.', correct: false },
      { sentence: 'The coffee isn\'t hot enough.', correct: true },
    ],
  },
  80: {
    rule: '"Quite" and "rather" modify adjectives. "Quite" = less than "very" (fairly). "Rather" = more than expected (somewhat negative or surprising).',
    formula: 'quite + adjective (= fairly) | rather + adjective (= more than expected)',
    examples: [
      { sentence: 'The film was quite good. (= fairly good, not amazing)', correct: true },
      { sentence: 'The exam was rather difficult. (= more difficult than expected)', correct: true },
      { sentence: 'It\'s quite cold today. (= fairly cold)', correct: true },
      { sentence: 'She\'s rather shy. (= surprisingly shy)', correct: true },
      { sentence: 'The food was quite nice. I enjoyed it.', correct: true },
      { sentence: 'I was rather surprised to see him there.', correct: true },
    ],
  },

  // ===== CONJUNCTIONS & WORD ORDER (Units 81-90) =====
  81: {
    rule: '"Although / though / even though" introduce a contrast. "In spite of / despite" + noun or -ing.',
    formula: 'although + clause | in spite of / despite + noun/-ing',
    examples: [
      { sentence: 'Although it rained, we enjoyed the trip.', correct: true },
      { sentence: 'In spite of the rain, we enjoyed the trip.', correct: true },
      { sentence: 'Despite being tired, she finished the work.', correct: true },
      { sentence: 'Even though I was scared, I jumped.', correct: true },
      { sentence: 'In spite of it rained, we enjoyed the trip.', correct: false },
      { sentence: 'In spite of the rain, we enjoyed the trip.', correct: true },
    ],
    notes: [
      '"Although" + subject + verb (a clause). "In spite of / despite" + noun or -ing (NOT a clause).',
      '"Despite the fact that + clause" is also correct: "Despite the fact that it rained…"',
    ],
  },
  82: {
    rule: '"In case" = because something might happen (precaution). "Unless" = except if / if … not.',
    formula: 'in case + present (precaution) | unless + present (= if not)',
    examples: [
      { sentence: 'Take an umbrella in case it rains. (= because it might rain)', correct: true },
      { sentence: 'I\'ll take an umbrella if it rains. (= only if it rains)', correct: true },
      { sentence: 'I won\'t go unless you come with me. (= if you don\'t come)', correct: true },
      { sentence: 'You can borrow my car as long as you drive carefully.', correct: true },
      { sentence: 'I wrote down her number in case I forgot it.', correct: true },
      { sentence: 'Unless you hurry, we\'ll be late.', correct: true },
    ],
    notes: [
      '"In case" ≠ "if". "I\'ll take an umbrella in case it rains" = I\'ll take it NOW, as a precaution.',
      '"As long as" / "provided that" = only if, on the condition that.',
    ],
  },
  83: {
    rule: '"So" and "such" add emphasis. "So + adjective/adverb". "Such + (adjective) + noun".',
    formula: 'so + adjective/adverb | such + (a/an) + (adjective) + noun',
    examples: [
      { sentence: 'The weather was so nice that we went to the beach.', correct: true },
      { sentence: 'It was such a nice day that we went to the beach.', correct: true },
      { sentence: 'She speaks so quickly that I can\'t understand her.', correct: true },
      { sentence: 'He\'s such a kind person.', correct: true },
      { sentence: 'It was so a nice day.', correct: false },
      { sentence: 'It was such nice weather.', correct: true },
    ],
    notes: [
      '"So" + adj/adv: "so hot", "so quickly". "Such" + noun: "such a hot day", "such nice weather".',
      'With uncountable/plural: "such nice weather" / "such lovely people" (no "a/an").',
    ],
  },
  84: {
    rule: '"For", "during", and "while" — "for" + how long, "during" + noun (when), "while" + clause (at the same time).',
    formula: 'for + period | during + noun | while + subject + verb',
    examples: [
      { sentence: 'I waited for 30 minutes.', correct: true },
      { sentence: 'I fell asleep during the film.', correct: true },
      { sentence: 'I fell asleep while I was watching TV.', correct: true },
      { sentence: 'We lived in Paris for six months.', correct: true },
      { sentence: 'During I was on holiday, it rained every day.', correct: false },
      { sentence: 'While I was on holiday, it rained every day.', correct: true },
    ],
  },
  85: {
    rule: '"By" and "until" — "by" = not later than (deadline). "Until" = up to that time (continuous).',
    formula: 'by + time (deadline) | until + time (up to)',
    examples: [
      { sentence: 'I\'ll be home by 6 o\'clock. (= not later than 6)', correct: true },
      { sentence: 'I\'ll be at work until 6 o\'clock. (= from now to 6)', correct: true },
      { sentence: 'The report must be finished by Friday.', correct: true },
      { sentence: 'I waited until she came back.', correct: true },
      { sentence: 'By the time I got there, the show had started.', correct: true },
      { sentence: 'We sat on the beach until it got dark.', correct: true },
    ],
  },
  86: {
    rule: '"At / on / in" for time: "at" = exact time/moment, "on" = days/dates, "in" = longer periods.',
    formula: 'at + time/moment | on + day/date | in + month/year/season/period',
    examples: [
      { sentence: 'I start work at 9 o\'clock.', correct: true },
      { sentence: 'The meeting is on Monday.', correct: true },
      { sentence: 'She was born in June / in 1995 / in the summer.', correct: true },
      { sentence: 'at night, at the weekend, at Christmas, at the moment', correct: true },
      { sentence: 'on Monday morning, on my birthday, on 6 March', correct: true },
      { sentence: 'We don\'t use at/on/in before: last, next, this, every.', correct: true },
    ],
  },
  87: {
    rule: '"In", "at", "on" for place: "in" = inside/area, "at" = point/location, "on" = surface/line.',
    formula: 'in + enclosed space/area | at + point/building | on + surface/road',
    examples: [
      { sentence: 'She\'s in the kitchen / in London / in a taxi.', correct: true },
      { sentence: 'I\'ll meet you at the station / at the door.', correct: true },
      { sentence: 'The picture is on the wall / on the second floor.', correct: true },
      { sentence: 'I was at home / at work / at school.', correct: true },
      { sentence: 'He lives in Baker Street.', correct: false },
      { sentence: 'He lives on Baker Street. (or "in" in British English)', correct: true },
    ],
  },
  88: {
    rule: '"To", "at", "in", "into" for movement and position. "To" = direction. "At/in" = position. "Into" = entering.',
    formula: 'go to + place | be at/in + place | go into + enclosed space',
    examples: [
      { sentence: 'I\'m going to work. (= direction)', correct: true },
      { sentence: 'I\'m at work. (= position)', correct: true },
      { sentence: 'She got into the car and drove away. (= entering)', correct: true },
      { sentence: 'I\'ve been to Paris twice. (= visited and returned)', correct: true },
      { sentence: 'I went to home.', correct: false },
      { sentence: 'I went home. (no "to" before home)', correct: true },
    ],
  },
  89: {
    rule: '"By" for how (method/means), who did it, and deadline. Also used in passive voice and various expressions.',
    formula: 'by + method/means | by + agent (passive) | by + deadline',
    examples: [
      { sentence: 'I came by bus / by car / by train.', correct: true },
      { sentence: 'The book was written by Tolkien. (= agent)', correct: true },
      { sentence: 'I\'ll be ready by 10 o\'clock. (= deadline)', correct: true },
      { sentence: 'She lives by herself. (= alone)', correct: true },
      { sentence: 'I went there by foot.', correct: false },
      { sentence: 'I went there on foot. (exception!)', correct: true },
    ],
  },
  90: {
    rule: 'Word order in English sentences: Subject + Verb + Object. Adverbs of frequency go before the main verb but after "be".',
    formula: 'S + V + O | S + frequency adverb + V | S + be + frequency adverb',
    examples: [
      { sentence: 'I always have breakfast at 8. (= adverb before verb)', correct: true },
      { sentence: 'She is always late. (= adverb after "be")', correct: true },
      { sentence: 'I also like pizza. (= "also" before verb)', correct: true },
      { sentence: 'He probably won\'t come. (= before "won\'t")', correct: true },
      { sentence: 'They gave me a present. (= S + V + indirect O + direct O)', correct: true },
      { sentence: 'I always am late.', correct: false },
    ],
  },
}
