// Seed vocabulary: ~350 words across A2-B2, organized by topic
// Format: [word, translation (ru), example, cefr, topic]

export type VocabSeed = {
  word: string
  translation: string
  example: string
  cefrLevel: 'A2' | 'B1' | 'B2'
  topic: string
}

const rows: Array<[string, string, string, 'A2' | 'B1' | 'B2', string]> = [
  // ===== A2: EVERYDAY LIFE =====
  ['neighbour', 'сосед', 'My neighbour is a very kind person.', 'A2', 'people'],
  ['relative', 'родственник', 'I have many relatives in the south.', 'A2', 'people'],
  ['colleague', 'коллега', 'My colleagues are all from different countries.', 'A2', 'work'],
  ['stranger', 'незнакомец', 'Don\'t talk to strangers.', 'A2', 'people'],
  ['guest', 'гость', 'We have guests coming for dinner tonight.', 'A2', 'people'],
  ['owner', 'владелец', 'Who is the owner of this car?', 'A2', 'people'],
  ['customer', 'покупатель', 'The customer is always right.', 'A2', 'work'],
  ['employee', 'сотрудник', 'She\'s been an employee here for ten years.', 'A2', 'work'],
  ['manager', 'менеджер', 'I need to speak to the manager.', 'A2', 'work'],
  ['boss', 'начальник', 'My boss gave me a pay rise.', 'A2', 'work'],

  // A2: HOME & FURNITURE
  ['furniture', 'мебель', 'The furniture in my flat is old.', 'A2', 'home'],
  ['shelf', 'полка', 'Put the book on the shelf.', 'A2', 'home'],
  ['drawer', 'ящик', 'My socks are in the top drawer.', 'A2', 'home'],
  ['curtain', 'занавеска', 'Please close the curtains, it\'s too bright.', 'A2', 'home'],
  ['carpet', 'ковёр', 'There\'s a beautiful carpet on the floor.', 'A2', 'home'],
  ['pillow', 'подушка', 'This pillow is too hard for me.', 'A2', 'home'],
  ['blanket', 'одеяло', 'It\'s cold — bring another blanket.', 'A2', 'home'],
  ['ceiling', 'потолок', 'The ceiling in this room is very high.', 'A2', 'home'],
  ['corner', 'угол', 'The lamp is in the corner of the room.', 'A2', 'home'],
  ['entrance', 'вход', 'The main entrance is on the left.', 'A2', 'home'],

  // A2: FOOD & EATING
  ['recipe', 'рецепт', 'Can you share the recipe for this cake?', 'A2', 'food'],
  ['ingredient', 'ингредиент', 'We need eggs and flour as main ingredients.', 'A2', 'food'],
  ['taste', 'вкус', 'This soup has a wonderful taste.', 'A2', 'food'],
  ['flavour', 'аромат/вкус', 'I love the flavour of fresh basil.', 'A2', 'food'],
  ['dish', 'блюдо', 'This is my favourite dish.', 'A2', 'food'],
  ['meal', 'еда (приём пищи)', 'Breakfast is the most important meal.', 'A2', 'food'],
  ['snack', 'перекус', 'Let\'s have a quick snack before the meeting.', 'A2', 'food'],
  ['dessert', 'десерт', 'What\'s for dessert tonight?', 'A2', 'food'],
  ['vegetable', 'овощ', 'Eat more vegetables — they\'re healthy.', 'A2', 'food'],
  ['knife', 'нож', 'Be careful with that sharp knife.', 'A2', 'food'],
  ['fork', 'вилка', 'You need a fork and a spoon for pasta.', 'A2', 'food'],
  ['plate', 'тарелка', 'Put the plates on the table, please.', 'A2', 'food'],

  // A2: WEATHER & NATURE
  ['weather', 'погода', 'What\'s the weather like today?', 'A2', 'nature'],
  ['forecast', 'прогноз', 'The forecast says it will rain tomorrow.', 'A2', 'nature'],
  ['temperature', 'температура', 'The temperature dropped suddenly.', 'A2', 'nature'],
  ['storm', 'шторм/буря', 'A big storm is coming.', 'A2', 'nature'],
  ['thunder', 'гром', 'I heard thunder in the distance.', 'A2', 'nature'],
  ['lightning', 'молния', 'Lightning struck a tree near our house.', 'A2', 'nature'],
  ['fog', 'туман', 'We couldn\'t drive because of the fog.', 'A2', 'nature'],
  ['breeze', 'бриз/лёгкий ветер', 'There\'s a nice cool breeze today.', 'A2', 'nature'],
  ['hill', 'холм', 'Our house is on top of a small hill.', 'A2', 'nature'],
  ['valley', 'долина', 'The valley is green in spring.', 'A2', 'nature'],

  // A2: DAILY ROUTINE
  ['routine', 'распорядок дня', 'My daily routine is quite simple.', 'A2', 'daily life'],
  ['habit', 'привычка', 'Reading before bed is a good habit.', 'A2', 'daily life'],
  ['hobby', 'хобби', 'My hobby is photography.', 'A2', 'daily life'],
  ['exercise', 'упражнение', 'I do exercise every morning.', 'A2', 'daily life'],
  ['rest', 'отдых', 'You need to rest after working so much.', 'A2', 'daily life'],
  ['chore', 'домашняя обязанность', 'I hate doing household chores.', 'A2', 'daily life'],
  ['laundry', 'стирка', 'I need to do the laundry today.', 'A2', 'daily life'],
  ['shopping', 'покупки', 'Let\'s go shopping this weekend.', 'A2', 'daily life'],

  // A2: EMOTIONS & FEELINGS
  ['mood', 'настроение', 'She\'s in a good mood today.', 'A2', 'emotions'],
  ['feeling', 'чувство', 'I have a strange feeling about this.', 'A2', 'emotions'],
  ['surprise', 'сюрприз', 'What a lovely surprise!', 'A2', 'emotions'],
  ['worry', 'беспокоиться', 'Don\'t worry about it.', 'A2', 'emotions'],
  ['proud', 'гордый', 'I\'m proud of my daughter.', 'A2', 'emotions'],
  ['lonely', 'одинокий', 'She feels lonely living alone.', 'A2', 'emotions'],
  ['nervous', 'нервный', 'I\'m nervous before the interview.', 'A2', 'emotions'],
  ['shy', 'застенчивый', 'He\'s too shy to speak in public.', 'A2', 'emotions'],
  ['calm', 'спокойный', 'Try to stay calm in difficult situations.', 'A2', 'emotions'],
  ['upset', 'расстроенный', 'Why are you so upset?', 'A2', 'emotions'],

  // A2: TRANSPORT
  ['journey', 'путешествие', 'Have a safe journey home.', 'A2', 'transport'],
  ['trip', 'поездка', 'We took a trip to the mountains.', 'A2', 'transport'],
  ['passenger', 'пассажир', 'All passengers must wear seatbelts.', 'A2', 'transport'],
  ['ticket', 'билет', 'I bought a ticket for the concert.', 'A2', 'transport'],
  ['platform', 'платформа', 'The train leaves from platform 5.', 'A2', 'transport'],
  ['traffic', 'движение/трафик', 'The traffic was terrible this morning.', 'A2', 'transport'],
  ['bridge', 'мост', 'We crossed the old stone bridge.', 'A2', 'transport'],
  ['highway', 'шоссе', 'There was an accident on the highway.', 'A2', 'transport'],

  // ===== B1: WORK & STUDY =====
  ['career', 'карьера', 'She\'s building an impressive career in law.', 'B1', 'work'],
  ['salary', 'зарплата', 'He asked for a higher salary.', 'B1', 'work'],
  ['interview', 'собеседование', 'I have a job interview tomorrow.', 'B1', 'work'],
  ['CV / resume', 'резюме', 'Please send your CV to this email.', 'B1', 'work'],
  ['colleague', 'коллега', 'My colleagues helped me with the project.', 'B1', 'work'],
  ['deadline', 'дедлайн', 'We must meet the deadline at all costs.', 'B1', 'work'],
  ['meeting', 'встреча', 'The meeting starts at 10 o\'clock.', 'B1', 'work'],
  ['project', 'проект', 'I\'m working on a new project.', 'B1', 'work'],
  ['skill', 'навык', 'Good communication is an important skill.', 'B1', 'work'],
  ['experience', 'опыт', 'She has five years of experience.', 'B1', 'work'],
  ['achievement', 'достижение', 'Winning that award was a huge achievement.', 'B1', 'work'],
  ['responsibility', 'ответственность', 'It\'s your responsibility to check the details.', 'B1', 'work'],
  ['task', 'задача', 'I have several tasks to finish today.', 'B1', 'work'],
  ['promotion', 'повышение', 'She got a promotion last month.', 'B1', 'work'],
  ['colleague', 'коллега', 'We often go for lunch with colleagues.', 'B1', 'work'],
  ['industry', 'отрасль', 'He works in the tech industry.', 'B1', 'work'],
  ['workplace', 'рабочее место', 'A friendly workplace boosts productivity.', 'B1', 'work'],
  ['overtime', 'сверхурочные', 'I don\'t want to work overtime tonight.', 'B1', 'work'],

  // B1: EDUCATION
  ['university', 'университет', 'He studies at Cambridge University.', 'B1', 'education'],
  ['degree', 'степень', 'She has a degree in economics.', 'B1', 'education'],
  ['graduate', 'выпускник', 'He\'s a recent graduate of Oxford.', 'B1', 'education'],
  ['scholarship', 'стипендия', 'She won a full scholarship to study abroad.', 'B1', 'education'],
  ['tuition', 'плата за обучение', 'Tuition fees are very high here.', 'B1', 'education'],
  ['subject', 'предмет', 'Maths was my favourite subject at school.', 'B1', 'education'],
  ['lecture', 'лекция', 'The lecture was fascinating.', 'B1', 'education'],
  ['assignment', 'задание', 'I have to finish this assignment by Friday.', 'B1', 'education'],
  ['exam', 'экзамен', 'I\'m studying hard for the exam.', 'B1', 'education'],
  ['grade', 'оценка', 'He got a good grade in his essay.', 'B1', 'education'],
  ['knowledge', 'знания', 'Her knowledge of history is impressive.', 'B1', 'education'],
  ['research', 'исследование', 'She\'s doing research on climate change.', 'B1', 'education'],

  // B1: HEALTH
  ['health', 'здоровье', 'Good food is important for health.', 'B1', 'health'],
  ['symptom', 'симптом', 'Fever is a common symptom of flu.', 'B1', 'health'],
  ['treatment', 'лечение', 'The treatment takes two weeks.', 'B1', 'health'],
  ['medicine', 'лекарство', 'Take this medicine twice a day.', 'B1', 'health'],
  ['illness', 'болезнь', 'He recovered from a serious illness.', 'B1', 'health'],
  ['injury', 'травма', 'He had to miss the game due to injury.', 'B1', 'health'],
  ['pain', 'боль', 'I have a terrible pain in my back.', 'B1', 'health'],
  ['exhausted', 'изнурённый', 'I\'m completely exhausted after that walk.', 'B1', 'health'],
  ['recover', 'выздоравливать', 'It took weeks to recover from the flu.', 'B1', 'health'],
  ['healthy', 'здоровый', 'Eating vegetables helps you stay healthy.', 'B1', 'health'],
  ['appointment', 'приём', 'I have a doctor\'s appointment at 3.', 'B1', 'health'],

  // B1: TRAVEL
  ['destination', 'место назначения', 'Our final destination is Tokyo.', 'B1', 'travel'],
  ['accommodation', 'проживание', 'The accommodation was very comfortable.', 'B1', 'travel'],
  ['reservation', 'бронирование', 'I made a reservation for two nights.', 'B1', 'travel'],
  ['luggage', 'багаж', 'I packed my luggage last night.', 'B1', 'travel'],
  ['passport', 'паспорт', 'Don\'t forget your passport!', 'B1', 'travel'],
  ['flight', 'рейс', 'Our flight was delayed by two hours.', 'B1', 'travel'],
  ['delay', 'задержка', 'There was a long delay at the airport.', 'B1', 'travel'],
  ['currency', 'валюта', 'What\'s the local currency in Japan?', 'B1', 'travel'],
  ['souvenir', 'сувенир', 'I bought a souvenir from every city we visited.', 'B1', 'travel'],
  ['guide', 'гид', 'Our tour guide was very knowledgeable.', 'B1', 'travel'],
  ['abroad', 'за границу', 'Have you ever travelled abroad?', 'B1', 'travel'],
  ['tourist', 'турист', 'There are many tourists in Rome in summer.', 'B1', 'travel'],
  ['landscape', 'пейзаж', 'The landscape in Scotland is breathtaking.', 'B1', 'travel'],

  // B1: TECHNOLOGY
  ['device', 'устройство', 'This device connects to the internet.', 'B1', 'technology'],
  ['software', 'программное обеспечение', 'I need to update the software.', 'B1', 'technology'],
  ['password', 'пароль', 'I forgot my password again.', 'B1', 'technology'],
  ['screen', 'экран', 'The screen is broken.', 'B1', 'technology'],
  ['charger', 'зарядное устройство', 'Can I borrow your charger?', 'B1', 'technology'],
  ['backup', 'резервная копия', 'Always make a backup of important files.', 'B1', 'technology'],
  ['download', 'скачивать', 'I downloaded the new album.', 'B1', 'technology'],
  ['upload', 'загружать', 'Please upload the file to the server.', 'B1', 'technology'],
  ['browser', 'браузер', 'Which browser do you use?', 'B1', 'technology'],
  ['crash', 'сбой', 'My computer crashed three times today.', 'B1', 'technology'],
  ['settings', 'настройки', 'Go to settings to change your preferences.', 'B1', 'technology'],
  ['notification', 'уведомление', 'I turned off all notifications.', 'B1', 'technology'],

  // B1: SHOPPING & MONEY
  ['afford', 'позволить себе', 'I can\'t afford a new car right now.', 'B1', 'money'],
  ['bargain', 'выгодная покупка', 'This jacket was a real bargain.', 'B1', 'money'],
  ['expensive', 'дорогой', 'That restaurant is too expensive for me.', 'B1', 'money'],
  ['cheap', 'дешёвый', 'I got these shoes very cheap.', 'B1', 'money'],
  ['discount', 'скидка', 'They gave me a 20% discount.', 'B1', 'money'],
  ['receipt', 'чек', 'Keep the receipt in case you want a refund.', 'B1', 'money'],
  ['refund', 'возврат денег', 'I asked for a refund.', 'B1', 'money'],
  ['cash', 'наличные', 'Do you take cash or only card?', 'B1', 'money'],
  ['borrow', 'брать взаймы', 'Can I borrow your pen?', 'B1', 'money'],
  ['lend', 'одалживать', 'I\'ll lend you the money, no problem.', 'B1', 'money'],
  ['save', 'копить', 'I\'m saving up for a holiday.', 'B1', 'money'],
  ['spend', 'тратить', 'I spent too much money this month.', 'B1', 'money'],
  ['waste', 'тратить впустую', 'Don\'t waste your time on this.', 'B1', 'money'],

  // ===== B2: ABSTRACT & ADVANCED =====
  ['achieve', 'достигать', 'She achieved great success in her career.', 'B2', 'abstract'],
  ['approach', 'подход', 'We need a different approach to this problem.', 'B2', 'abstract'],
  ['assume', 'предполагать', 'Don\'t assume everyone thinks like you.', 'B2', 'abstract'],
  ['aware', 'осведомлённый', 'Are you aware of the risks?', 'B2', 'abstract'],
  ['benefit', 'польза/выгода', 'Exercise has many benefits for your health.', 'B2', 'abstract'],
  ['challenge', 'вызов', 'Learning a new language is a real challenge.', 'B2', 'abstract'],
  ['circumstance', 'обстоятельство', 'Under these circumstances, we must act fast.', 'B2', 'abstract'],
  ['concept', 'концепция', 'The concept of time is hard to define.', 'B2', 'abstract'],
  ['conclusion', 'вывод', 'What conclusion can we draw from this?', 'B2', 'abstract'],
  ['consequence', 'последствие', 'Every action has a consequence.', 'B2', 'abstract'],
  ['consider', 'учитывать', 'Have you considered all the options?', 'B2', 'abstract'],
  ['contribute', 'способствовать', 'Everyone contributed to the project.', 'B2', 'abstract'],
  ['convince', 'убеждать', 'I couldn\'t convince him to come with us.', 'B2', 'abstract'],
  ['current', 'нынешний', 'What is your current job?', 'B2', 'abstract'],
  ['define', 'определять', 'Can you define the word "happiness"?', 'B2', 'abstract'],
  ['demand', 'требование/спрос', 'There\'s high demand for skilled workers.', 'B2', 'abstract'],
  ['determine', 'определять', 'Your hard work will determine your success.', 'B2', 'abstract'],
  ['develop', 'развивать', 'We developed a new training programme.', 'B2', 'abstract'],
  ['emphasise', 'подчёркивать', 'She emphasised the importance of honesty.', 'B2', 'abstract'],
  ['ensure', 'обеспечивать', 'Please ensure the door is locked.', 'B2', 'abstract'],
  ['essential', 'существенный', 'Water is essential for life.', 'B2', 'abstract'],
  ['estimate', 'оценивать', 'I estimate it will cost around $500.', 'B2', 'abstract'],
  ['evidence', 'доказательство', 'There\'s no evidence to support his claim.', 'B2', 'abstract'],
  ['examine', 'исследовать', 'The doctor examined me carefully.', 'B2', 'abstract'],
  ['factor', 'фактор', 'Several factors influenced the decision.', 'B2', 'abstract'],
  ['focus', 'фокус', 'Let\'s focus on what\'s important.', 'B2', 'abstract'],
  ['fundamental', 'фундаментальный', 'Trust is a fundamental part of friendship.', 'B2', 'abstract'],
  ['generate', 'создавать', 'Solar panels generate electricity.', 'B2', 'abstract'],
  ['impact', 'влияние', 'The new law will have a big impact.', 'B2', 'abstract'],
  ['implement', 'внедрять', 'We need to implement these changes quickly.', 'B2', 'abstract'],
  ['implication', 'последствие', 'I hadn\'t considered the implications.', 'B2', 'abstract'],
  ['indicate', 'указывать', 'The sign indicates the way to the station.', 'B2', 'abstract'],
  ['inevitable', 'неизбежный', 'Change is inevitable.', 'B2', 'abstract'],
  ['influence', 'влиять', 'Parents greatly influence their children.', 'B2', 'abstract'],
  ['investigate', 'расследовать', 'Police are investigating the crime.', 'B2', 'abstract'],
  ['involve', 'включать в себя', 'My job involves a lot of travel.', 'B2', 'abstract'],
  ['maintain', 'поддерживать', 'It\'s important to maintain good relationships.', 'B2', 'abstract'],
  ['obvious', 'очевидный', 'It\'s obvious he\'s lying.', 'B2', 'abstract'],
  ['occur', 'происходить', 'The accident occurred at midnight.', 'B2', 'abstract'],
  ['perspective', 'перспектива/взгляд', 'Try to see things from my perspective.', 'B2', 'abstract'],
  ['phenomenon', 'феномен', 'This is a rare natural phenomenon.', 'B2', 'abstract'],
  ['potential', 'потенциал', 'She has great potential as a writer.', 'B2', 'abstract'],
  ['prevent', 'предотвращать', 'We must prevent similar accidents.', 'B2', 'abstract'],
  ['provide', 'предоставлять', 'The hotel provides free breakfast.', 'B2', 'abstract'],
  ['reduce', 'уменьшать', 'We need to reduce our spending.', 'B2', 'abstract'],
  ['reveal', 'раскрывать', 'The study revealed surprising results.', 'B2', 'abstract'],
  ['significant', 'значительный', 'There\'s a significant difference.', 'B2', 'abstract'],
  ['struggle', 'борьба', 'Many students struggle with maths.', 'B2', 'abstract'],
  ['suggest', 'предлагать', 'I suggest we take a break.', 'B2', 'abstract'],
  ['sufficient', 'достаточный', 'Is this sufficient for your needs?', 'B2', 'abstract'],
  ['tend', 'иметь тенденцию', 'I tend to wake up early.', 'B2', 'abstract'],
  ['transform', 'преобразовывать', 'The internet transformed communication.', 'B2', 'abstract'],

  // B2: PHRASAL VERBS
  ['give up', 'сдаваться', 'Never give up on your dreams.', 'B2', 'phrasal verbs'],
  ['come up with', 'придумывать', 'She came up with a brilliant idea.', 'B2', 'phrasal verbs'],
  ['look forward to', 'ждать с нетерпением', 'I\'m looking forward to seeing you.', 'B2', 'phrasal verbs'],
  ['put off', 'откладывать', 'Don\'t put off until tomorrow what you can do today.', 'B2', 'phrasal verbs'],
  ['get along with', 'ладить с', 'I get along with my coworkers.', 'B2', 'phrasal verbs'],
  ['look after', 'присматривать за', 'Can you look after my cat this weekend?', 'B2', 'phrasal verbs'],
  ['run out of', 'заканчиваться', 'We\'ve run out of milk.', 'B2', 'phrasal verbs'],
  ['take up', 'заняться', 'She took up yoga last year.', 'B2', 'phrasal verbs'],
  ['turn down', 'отклонять', 'He turned down the job offer.', 'B2', 'phrasal verbs'],
  ['work out', 'получаться / тренироваться', 'Everything will work out in the end.', 'B2', 'phrasal verbs'],
  ['break down', 'ломаться', 'My car broke down on the motorway.', 'B2', 'phrasal verbs'],
  ['bring up', 'воспитывать / поднимать тему', 'She was brought up by her grandparents.', 'B2', 'phrasal verbs'],
  ['call off', 'отменять', 'They called off the wedding.', 'B2', 'phrasal verbs'],
  ['carry out', 'осуществлять', 'We need to carry out more tests.', 'B2', 'phrasal verbs'],
  ['end up', 'в итоге оказаться', 'We ended up watching TV all night.', 'B2', 'phrasal verbs'],
  ['figure out', 'разобраться', 'I can\'t figure out how this works.', 'B2', 'phrasal verbs'],
  ['get rid of', 'избавляться', 'I need to get rid of these old clothes.', 'B2', 'phrasal verbs'],
  ['go through', 'переживать', 'She\'s going through a difficult time.', 'B2', 'phrasal verbs'],
  ['keep up with', 'поспевать за', 'I can\'t keep up with all the changes.', 'B2', 'phrasal verbs'],
  ['look into', 'изучать вопрос', 'The police are looking into the matter.', 'B2', 'phrasal verbs'],
  ['make up', 'придумывать / мириться', 'He made up the whole story.', 'B2', 'phrasal verbs'],
  ['pick up', 'забирать', 'I\'ll pick you up at the airport.', 'B2', 'phrasal verbs'],
  ['point out', 'указывать', 'She pointed out my mistake.', 'B2', 'phrasal verbs'],
  ['set up', 'создавать/учреждать', 'They set up a new company.', 'B2', 'phrasal verbs'],
  ['show up', 'появляться', 'He didn\'t show up for the meeting.', 'B2', 'phrasal verbs'],
  ['sort out', 'разбираться', 'Let\'s sort out this problem now.', 'B2', 'phrasal verbs'],

  // B2: COMMON COLLOCATIONS
  ['make a decision', 'принять решение', 'We need to make a decision quickly.', 'B2', 'collocations'],
  ['take a risk', 'рисковать', 'Sometimes you need to take a risk.', 'B2', 'collocations'],
  ['pay attention', 'обращать внимание', 'Pay attention to the details.', 'B2', 'collocations'],
  ['make progress', 'делать успехи', 'She\'s making good progress in English.', 'B2', 'collocations'],
  ['take advantage of', 'воспользоваться', 'Take advantage of the free trial.', 'B2', 'collocations'],
  ['do research', 'проводить исследование', 'He does research at the university.', 'B2', 'collocations'],
  ['meet a deadline', 'уложиться в срок', 'We must meet the deadline.', 'B2', 'collocations'],
  ['have an impact', 'оказывать влияние', 'The news had a huge impact on me.', 'B2', 'collocations'],
  ['make an effort', 'приложить усилия', 'She made an effort to be polite.', 'B2', 'collocations'],
  ['take responsibility', 'брать ответственность', 'You must take responsibility for your actions.', 'B2', 'collocations'],
  ['draw a conclusion', 'делать вывод', 'It\'s too early to draw any conclusions.', 'B2', 'collocations'],
  ['run a business', 'управлять бизнесом', 'She runs her own business.', 'B2', 'collocations'],
  ['catch a cold', 'простудиться', 'I caught a cold last week.', 'B2', 'collocations'],
  ['break a promise', 'нарушить обещание', 'He broke his promise again.', 'B2', 'collocations'],
  ['keep in touch', 'поддерживать связь', 'Let\'s keep in touch by email.', 'B2', 'collocations'],
]

export const vocabularySeed: VocabSeed[] = rows.map(([word, translation, example, cefrLevel, topic]) => ({
  word,
  translation,
  example,
  cefrLevel,
  topic,
}))
