// Seed vocabulary: ~350 words across A2-B2, organized by topic
// Format: [word, translation (ru), example, cefr, topic]

export type VocabSeed = {
  word: string
  translation: string
  example: string
  cefrLevel: 'A2' | 'B1' | 'B2' | 'C1'
  topic: string
}

const rows: Array<[string, string, string, 'A2' | 'B1' | 'B2' | 'C1', string]> = [
  // ===== A2: EVERYDAY LIFE =====
  ['neighbour', 'сосед', 'My neighbour is a very kind person.', 'A2', 'people'],
  ['relative', 'родственник', 'I have many relatives in the south.', 'A2', 'people'],
  ['colleague', 'коллега', 'My colleagues are all from different countries.', 'A2', 'work'],
  ['stranger', 'незнакомец', 'Don\'t talk to strangers.', 'A2', 'people'],
  ['guest', 'гость', 'We have guests coming for dinner tonight.', 'A2', 'people'],
  ['owner', 'владелец', 'Who is the owner of this car?', 'A2', 'people'],
  ['customer', 'покупатель', 'The customer is always right.', 'A2', 'work'],
  ['employee', 'сотрудник', 'She\'s been an employee here for ten years.', 'A2', 'work'],
  ['manager', 'менеджер', 'I need to speak to the manager.', 'A2', 'work'],
  ['boss', 'начальник', 'My boss gave me a pay rise.', 'A2', 'work'],

  // A2: HOME & FURNITURE
  ['furniture', 'мебель', 'The furniture in my flat is old.', 'A2', 'home'],
  ['shelf', 'полка', 'Put the book on the shelf.', 'A2', 'home'],
  ['drawer', 'ящик', 'My socks are in the top drawer.', 'A2', 'home'],
  ['curtain', 'занавеска', 'Please close the curtains, it\'s too bright.', 'A2', 'home'],
  ['carpet', 'ковёр', 'There\'s a beautiful carpet on the floor.', 'A2', 'home'],
  ['pillow', 'подушка', 'This pillow is too hard for me.', 'A2', 'home'],
  ['blanket', 'одеяло', 'It\'s cold — bring another blanket.', 'A2', 'home'],
  ['ceiling', 'потолок', 'The ceiling in this room is very high.', 'A2', 'home'],
  ['corner', 'угол', 'The lamp is in the corner of the room.', 'A2', 'home'],
  ['entrance', 'вход', 'The main entrance is on the left.', 'A2', 'home'],

  // A2: FOOD & EATING
  ['recipe', 'рецепт', 'Can you share the recipe for this cake?', 'A2', 'food'],
  ['ingredient', 'ингредиент', 'We need eggs and flour as main ingredients.', 'A2', 'food'],
  ['taste', 'вкус', 'This soup has a wonderful taste.', 'A2', 'food'],
  ['flavour', 'аромат/вкус', 'I love the flavour of fresh basil.', 'A2', 'food'],
  ['dish', 'блюдо', 'This is my favourite dish.', 'A2', 'food'],
  ['meal', 'еда (приём пищи)', 'Breakfast is the most important meal.', 'A2', 'food'],
  ['snack', 'перекус', 'Let\'s have a quick snack before the meeting.', 'A2', 'food'],
  ['dessert', 'десерт', 'What\'s for dessert tonight?', 'A2', 'food'],
  ['vegetable', 'овощ', 'Eat more vegetables — they\'re healthy.', 'A2', 'food'],
  ['knife', 'нож', 'Be careful with that sharp knife.', 'A2', 'food'],
  ['fork', 'вилка', 'You need a fork and a spoon for pasta.', 'A2', 'food'],
  ['plate', 'тарелка', 'Put the plates on the table, please.', 'A2', 'food'],

  // A2: WEATHER & NATURE
  ['weather', 'погода', 'What\'s the weather like today?', 'A2', 'nature'],
  ['forecast', 'прогноз', 'The forecast says it will rain tomorrow.', 'A2', 'nature'],
  ['temperature', 'температура', 'The temperature dropped suddenly.', 'A2', 'nature'],
  ['storm', 'шторм/буря', 'A big storm is coming.', 'A2', 'nature'],
  ['thunder', 'гром', 'I heard thunder in the distance.', 'A2', 'nature'],
  ['lightning', 'молния', 'Lightning struck a tree near our house.', 'A2', 'nature'],
  ['fog', 'туман', 'We couldn\'t drive because of the fog.', 'A2', 'nature'],
  ['breeze', 'бриз/лёгкий ветер', 'There\'s a nice cool breeze today.', 'A2', 'nature'],
  ['hill', 'холм', 'Our house is on top of a small hill.', 'A2', 'nature'],
  ['valley', 'долина', 'The valley is green in spring.', 'A2', 'nature'],

  // A2: DAILY ROUTINE
  ['routine', 'распорядок дня', 'My daily routine is quite simple.', 'A2', 'daily life'],
  ['habit', 'привычка', 'Reading before bed is a good habit.', 'A2', 'daily life'],
  ['hobby', 'хобби', 'My hobby is photography.', 'A2', 'daily life'],
  ['exercise', 'упражнение', 'I do exercise every morning.', 'A2', 'daily life'],
  ['rest', 'отдых', 'You need to rest after working so much.', 'A2', 'daily life'],
  ['chore', 'домашняя обязанность', 'I hate doing household chores.', 'A2', 'daily life'],
  ['laundry', 'стирка', 'I need to do the laundry today.', 'A2', 'daily life'],
  ['shopping', 'покупки', 'Let\'s go shopping this weekend.', 'A2', 'daily life'],

  // A2: EMOTIONS & FEELINGS
  ['mood', 'настроение', 'She\'s in a good mood today.', 'A2', 'emotions'],
  ['feeling', 'чувство', 'I have a strange feeling about this.', 'A2', 'emotions'],
  ['surprise', 'сюрприз', 'What a lovely surprise!', 'A2', 'emotions'],
  ['worry', 'беспокоиться', 'Don\'t worry about it.', 'A2', 'emotions'],
  ['proud', 'гордый', 'I\'m proud of my daughter.', 'A2', 'emotions'],
  ['lonely', 'одинокий', 'She feels lonely living alone.', 'A2', 'emotions'],
  ['nervous', 'нервный', 'I\'m nervous before the interview.', 'A2', 'emotions'],
  ['shy', 'застенчивый', 'He\'s too shy to speak in public.', 'A2', 'emotions'],
  ['calm', 'спокойный', 'Try to stay calm in difficult situations.', 'A2', 'emotions'],
  ['upset', 'расстроенный', 'Why are you so upset?', 'A2', 'emotions'],

  // A2: TRANSPORT
  ['journey', 'путешествие', 'Have a safe journey home.', 'A2', 'transport'],
  ['trip', 'поездка', 'We took a trip to the mountains.', 'A2', 'transport'],
  ['passenger', 'пассажир', 'All passengers must wear seatbelts.', 'A2', 'transport'],
  ['ticket', 'билет', 'I bought a ticket for the concert.', 'A2', 'transport'],
  ['platform', 'платформа', 'The train leaves from platform 5.', 'A2', 'transport'],
  ['traffic', 'движение/трафик', 'The traffic was terrible this morning.', 'A2', 'transport'],
  ['bridge', 'мост', 'We crossed the old stone bridge.', 'A2', 'transport'],
  ['highway', 'шоссе', 'There was an accident on the highway.', 'A2', 'transport'],

  // ===== B1: WORK & STUDY =====
  ['career', 'карьера', 'She\'s building an impressive career in law.', 'B1', 'work'],
  ['salary', 'зарплата', 'He asked for a higher salary.', 'B1', 'work'],
  ['interview', 'собеседование', 'I have a job interview tomorrow.', 'B1', 'work'],
  ['CV / resume', 'резюме', 'Please send your CV to this email.', 'B1', 'work'],
  ['colleague', 'коллега', 'My colleagues helped me with the project.', 'B1', 'work'],
  ['deadline', 'дедлайн', 'We must meet the deadline at all costs.', 'B1', 'work'],
  ['meeting', 'встреча', 'The meeting starts at 10 o\'clock.', 'B1', 'work'],
  ['project', 'проект', 'I\'m working on a new project.', 'B1', 'work'],
  ['skill', 'навык', 'Good communication is an important skill.', 'B1', 'work'],
  ['experience', 'опыт', 'She has five years of experience.', 'B1', 'work'],
  ['achievement', 'достижение', 'Winning that award was a huge achievement.', 'B1', 'work'],
  ['responsibility', 'ответственность', 'It\'s your responsibility to check the details.', 'B1', 'work'],
  ['task', 'задача', 'I have several tasks to finish today.', 'B1', 'work'],
  ['promotion', 'повышение', 'She got a promotion last month.', 'B1', 'work'],
  ['colleague', 'коллега', 'We often go for lunch with colleagues.', 'B1', 'work'],
  ['industry', 'отрасль', 'He works in the tech industry.', 'B1', 'work'],
  ['workplace', 'рабочее место', 'A friendly workplace boosts productivity.', 'B1', 'work'],
  ['overtime', 'сверхурочные', 'I don\'t want to work overtime tonight.', 'B1', 'work'],

  // B1: EDUCATION
  ['university', 'университет', 'He studies at Cambridge University.', 'B1', 'education'],
  ['degree', 'степень', 'She has a degree in economics.', 'B1', 'education'],
  ['graduate', 'выпускник', 'He\'s a recent graduate of Oxford.', 'B1', 'education'],
  ['scholarship', 'стипендия', 'She won a full scholarship to study abroad.', 'B1', 'education'],
  ['tuition', 'плата за обучение', 'Tuition fees are very high here.', 'B1', 'education'],
  ['subject', 'предмет', 'Maths was my favourite subject at school.', 'B1', 'education'],
  ['lecture', 'лекция', 'The lecture was fascinating.', 'B1', 'education'],
  ['assignment', 'задание', 'I have to finish this assignment by Friday.', 'B1', 'education'],
  ['exam', 'экзамен', 'I\'m studying hard for the exam.', 'B1', 'education'],
  ['grade', 'оценка', 'He got a good grade in his essay.', 'B1', 'education'],
  ['knowledge', 'знания', 'Her knowledge of history is impressive.', 'B1', 'education'],
  ['research', 'исследование', 'She\'s doing research on climate change.', 'B1', 'education'],

  // B1: HEALTH
  ['health', 'здоровье', 'Good food is important for health.', 'B1', 'health'],
  ['symptom', 'симптом', 'Fever is a common symptom of flu.', 'B1', 'health'],
  ['treatment', 'лечение', 'The treatment takes two weeks.', 'B1', 'health'],
  ['medicine', 'лекарство', 'Take this medicine twice a day.', 'B1', 'health'],
  ['illness', 'болезнь', 'He recovered from a serious illness.', 'B1', 'health'],
  ['injury', 'травма', 'He had to miss the game due to injury.', 'B1', 'health'],
  ['pain', 'боль', 'I have a terrible pain in my back.', 'B1', 'health'],
  ['exhausted', 'изнурённый', 'I\'m completely exhausted after that walk.', 'B1', 'health'],
  ['recover', 'выздоравливать', 'It took weeks to recover from the flu.', 'B1', 'health'],
  ['healthy', 'здоровый', 'Eating vegetables helps you stay healthy.', 'B1', 'health'],
  ['appointment', 'приём', 'I have a doctor\'s appointment at 3.', 'B1', 'health'],

  // B1: TRAVEL
  ['destination', 'место назначения', 'Our final destination is Tokyo.', 'B1', 'travel'],
  ['accommodation', 'проживание', 'The accommodation was very comfortable.', 'B1', 'travel'],
  ['reservation', 'бронирование', 'I made a reservation for two nights.', 'B1', 'travel'],
  ['luggage', 'багаж', 'I packed my luggage last night.', 'B1', 'travel'],
  ['passport', 'паспорт', 'Don\'t forget your passport!', 'B1', 'travel'],
  ['flight', 'рейс', 'Our flight was delayed by two hours.', 'B1', 'travel'],
  ['delay', 'задержка', 'There was a long delay at the airport.', 'B1', 'travel'],
  ['currency', 'валюта', 'What\'s the local currency in Japan?', 'B1', 'travel'],
  ['souvenir', 'сувенир', 'I bought a souvenir from every city we visited.', 'B1', 'travel'],
  ['guide', 'гид', 'Our tour guide was very knowledgeable.', 'B1', 'travel'],
  ['abroad', 'за границу', 'Have you ever travelled abroad?', 'B1', 'travel'],
  ['tourist', 'турист', 'There are many tourists in Rome in summer.', 'B1', 'travel'],
  ['landscape', 'пейзаж', 'The landscape in Scotland is breathtaking.', 'B1', 'travel'],

  // B1: TECHNOLOGY
  ['device', 'устройство', 'This device connects to the internet.', 'B1', 'technology'],
  ['software', 'программное обеспечение', 'I need to update the software.', 'B1', 'technology'],
  ['password', 'пароль', 'I forgot my password again.', 'B1', 'technology'],
  ['screen', 'экран', 'The screen is broken.', 'B1', 'technology'],
  ['charger', 'зарядное устройство', 'Can I borrow your charger?', 'B1', 'technology'],
  ['backup', 'резервная копия', 'Always make a backup of important files.', 'B1', 'technology'],
  ['download', 'скачивать', 'I downloaded the new album.', 'B1', 'technology'],
  ['upload', 'загружать', 'Please upload the file to the server.', 'B1', 'technology'],
  ['browser', 'браузер', 'Which browser do you use?', 'B1', 'technology'],
  ['crash', 'сбой', 'My computer crashed three times today.', 'B1', 'technology'],
  ['settings', 'настройки', 'Go to settings to change your preferences.', 'B1', 'technology'],
  ['notification', 'уведомление', 'I turned off all notifications.', 'B1', 'technology'],

  // B1: SHOPPING & MONEY
  ['afford', 'позволить себе', 'I can\'t afford a new car right now.', 'B1', 'money'],
  ['bargain', 'выгодная покупка', 'This jacket was a real bargain.', 'B1', 'money'],
  ['expensive', 'дорогой', 'That restaurant is too expensive for me.', 'B1', 'money'],
  ['cheap', 'дешёвый', 'I got these shoes very cheap.', 'B1', 'money'],
  ['discount', 'скидка', 'They gave me a 20% discount.', 'B1', 'money'],
  ['receipt', 'чек', 'Keep the receipt in case you want a refund.', 'B1', 'money'],
  ['refund', 'возврат денег', 'I asked for a refund.', 'B1', 'money'],
  ['cash', 'наличные', 'Do you take cash or only card?', 'B1', 'money'],
  ['borrow', 'брать взаймы', 'Can I borrow your pen?', 'B1', 'money'],
  ['lend', 'одалживать', 'I\'ll lend you the money, no problem.', 'B1', 'money'],
  ['save', 'копить', 'I\'m saving up for a holiday.', 'B1', 'money'],
  ['spend', 'тратить', 'I spent too much money this month.', 'B1', 'money'],
  ['waste', 'тратить впустую', 'Don\'t waste your time on this.', 'B1', 'money'],

  // ===== B2: ABSTRACT & ADVANCED =====
  ['achieve', 'достигать', 'She achieved great success in her career.', 'B2', 'abstract'],
  ['approach', 'подход', 'We need a different approach to this problem.', 'B2', 'abstract'],
  ['assume', 'предполагать', 'Don\'t assume everyone thinks like you.', 'B2', 'abstract'],
  ['aware', 'осведомлённый', 'Are you aware of the risks?', 'B2', 'abstract'],
  ['benefit', 'польза/выгода', 'Exercise has many benefits for your health.', 'B2', 'abstract'],
  ['challenge', 'вызов', 'Learning a new language is a real challenge.', 'B2', 'abstract'],
  ['circumstance', 'обстоятельство', 'Under these circumstances, we must act fast.', 'B2', 'abstract'],
  ['concept', 'концепция', 'The concept of time is hard to define.', 'B2', 'abstract'],
  ['conclusion', 'вывод', 'What conclusion can we draw from this?', 'B2', 'abstract'],
  ['consequence', 'последствие', 'Every action has a consequence.', 'B2', 'abstract'],
  ['consider', 'учитывать', 'Have you considered all the options?', 'B2', 'abstract'],
  ['contribute', 'способствовать', 'Everyone contributed to the project.', 'B2', 'abstract'],
  ['convince', 'убеждать', 'I couldn\'t convince him to come with us.', 'B2', 'abstract'],
  ['current', 'нынешний', 'What is your current job?', 'B2', 'abstract'],
  ['define', 'определять', 'Can you define the word "happiness"?', 'B2', 'abstract'],
  ['demand', 'требование/спрос', 'There\'s high demand for skilled workers.', 'B2', 'abstract'],
  ['determine', 'определять', 'Your hard work will determine your success.', 'B2', 'abstract'],
  ['develop', 'развивать', 'We developed a new training programme.', 'B2', 'abstract'],
  ['emphasise', 'подчёркивать', 'She emphasised the importance of honesty.', 'B2', 'abstract'],
  ['ensure', 'обеспечивать', 'Please ensure the door is locked.', 'B2', 'abstract'],
  ['essential', 'существенный', 'Water is essential for life.', 'B2', 'abstract'],
  ['estimate', 'оценивать', 'I estimate it will cost around $500.', 'B2', 'abstract'],
  ['evidence', 'доказательство', 'There\'s no evidence to support his claim.', 'B2', 'abstract'],
  ['examine', 'исследовать', 'The doctor examined me carefully.', 'B2', 'abstract'],
  ['factor', 'фактор', 'Several factors influenced the decision.', 'B2', 'abstract'],
  ['focus', 'фокус', 'Let\'s focus on what\'s important.', 'B2', 'abstract'],
  ['fundamental', 'фундаментальный', 'Trust is a fundamental part of friendship.', 'B2', 'abstract'],
  ['generate', 'создавать', 'Solar panels generate electricity.', 'B2', 'abstract'],
  ['impact', 'влияние', 'The new law will have a big impact.', 'B2', 'abstract'],
  ['implement', 'внедрять', 'We need to implement these changes quickly.', 'B2', 'abstract'],
  ['implication', 'последствие', 'I hadn\'t considered the implications.', 'B2', 'abstract'],
  ['indicate', 'указывать', 'The sign indicates the way to the station.', 'B2', 'abstract'],
  ['inevitable', 'неизбежный', 'Change is inevitable.', 'B2', 'abstract'],
  ['influence', 'влиять', 'Parents greatly influence their children.', 'B2', 'abstract'],
  ['investigate', 'расследовать', 'Police are investigating the crime.', 'B2', 'abstract'],
  ['involve', 'включать в себя', 'My job involves a lot of travel.', 'B2', 'abstract'],
  ['maintain', 'поддерживать', 'It\'s important to maintain good relationships.', 'B2', 'abstract'],
  ['obvious', 'очевидный', 'It\'s obvious he\'s lying.', 'B2', 'abstract'],
  ['occur', 'происходить', 'The accident occurred at midnight.', 'B2', 'abstract'],
  ['perspective', 'перспектива/взгляд', 'Try to see things from my perspective.', 'B2', 'abstract'],
  ['phenomenon', 'феномен', 'This is a rare natural phenomenon.', 'B2', 'abstract'],
  ['potential', 'потенциал', 'She has great potential as a writer.', 'B2', 'abstract'],
  ['prevent', 'предотвращать', 'We must prevent similar accidents.', 'B2', 'abstract'],
  ['provide', 'предоставлять', 'The hotel provides free breakfast.', 'B2', 'abstract'],
  ['reduce', 'уменьшать', 'We need to reduce our spending.', 'B2', 'abstract'],
  ['reveal', 'раскрывать', 'The study revealed surprising results.', 'B2', 'abstract'],
  ['significant', 'значительный', 'There\'s a significant difference.', 'B2', 'abstract'],
  ['struggle', 'борьба', 'Many students struggle with maths.', 'B2', 'abstract'],
  ['suggest', 'предлагать', 'I suggest we take a break.', 'B2', 'abstract'],
  ['sufficient', 'достаточный', 'Is this sufficient for your needs?', 'B2', 'abstract'],
  ['tend', 'иметь тенденцию', 'I tend to wake up early.', 'B2', 'abstract'],
  ['transform', 'преобразовывать', 'The internet transformed communication.', 'B2', 'abstract'],

  // B2: PHRASAL VERBS
  ['give up', 'сдаваться', 'Never give up on your dreams.', 'B2', 'phrasal verbs'],
  ['come up with', 'придумывать', 'She came up with a brilliant idea.', 'B2', 'phrasal verbs'],
  ['look forward to', 'ждать с нетерпением', 'I\'m looking forward to seeing you.', 'B2', 'phrasal verbs'],
  ['put off', 'откладывать', 'Don\'t put off until tomorrow what you can do today.', 'B2', 'phrasal verbs'],
  ['get along with', 'ладить с', 'I get along with my coworkers.', 'B2', 'phrasal verbs'],
  ['look after', 'присматривать за', 'Can you look after my cat this weekend?', 'B2', 'phrasal verbs'],
  ['run out of', 'заканчиваться', 'We\'ve run out of milk.', 'B2', 'phrasal verbs'],
  ['take up', 'заняться', 'She took up yoga last year.', 'B2', 'phrasal verbs'],
  ['turn down', 'отклонять', 'He turned down the job offer.', 'B2', 'phrasal verbs'],
  ['work out', 'получаться / тренироваться', 'Everything will work out in the end.', 'B2', 'phrasal verbs'],
  ['break down', 'ломаться', 'My car broke down on the motorway.', 'B2', 'phrasal verbs'],
  ['bring up', 'воспитывать / поднимать тему', 'She was brought up by her grandparents.', 'B2', 'phrasal verbs'],
  ['call off', 'отменять', 'They called off the wedding.', 'B2', 'phrasal verbs'],
  ['carry out', 'осуществлять', 'We need to carry out more tests.', 'B2', 'phrasal verbs'],
  ['end up', 'в итоге оказаться', 'We ended up watching TV all night.', 'B2', 'phrasal verbs'],
  ['figure out', 'разобраться', 'I can\'t figure out how this works.', 'B2', 'phrasal verbs'],
  ['get rid of', 'избавляться', 'I need to get rid of these old clothes.', 'B2', 'phrasal verbs'],
  ['go through', 'переживать', 'She\'s going through a difficult time.', 'B2', 'phrasal verbs'],
  ['keep up with', 'поспевать за', 'I can\'t keep up with all the changes.', 'B2', 'phrasal verbs'],
  ['look into', 'изучать вопрос', 'The police are looking into the matter.', 'B2', 'phrasal verbs'],
  ['make up', 'придумывать / мириться', 'He made up the whole story.', 'B2', 'phrasal verbs'],
  ['pick up', 'забирать', 'I\'ll pick you up at the airport.', 'B2', 'phrasal verbs'],
  ['point out', 'указывать', 'She pointed out my mistake.', 'B2', 'phrasal verbs'],
  ['set up', 'создавать/учреждать', 'They set up a new company.', 'B2', 'phrasal verbs'],
  ['show up', 'появляться', 'He didn\'t show up for the meeting.', 'B2', 'phrasal verbs'],
  ['sort out', 'разбираться', 'Let\'s sort out this problem now.', 'B2', 'phrasal verbs'],

  // B2: COMMON COLLOCATIONS
  ['make a decision', 'принять решение', 'We need to make a decision quickly.', 'B2', 'collocations'],
  ['take a risk', 'рисковать', 'Sometimes you need to take a risk.', 'B2', 'collocations'],
  ['pay attention', 'обращать внимание', 'Pay attention to the details.', 'B2', 'collocations'],
  ['make progress', 'делать успехи', 'She\'s making good progress in English.', 'B2', 'collocations'],
  ['take advantage of', 'воспользоваться', 'Take advantage of the free trial.', 'B2', 'collocations'],
  ['do research', 'проводить исследование', 'He does research at the university.', 'B2', 'collocations'],
  ['meet a deadline', 'уложиться в срок', 'We must meet the deadline.', 'B2', 'collocations'],
  ['have an impact', 'оказывать влияние', 'The news had a huge impact on me.', 'B2', 'collocations'],
  ['make an effort', 'приложить усилия', 'She made an effort to be polite.', 'B2', 'collocations'],
  ['take responsibility', 'брать ответственность', 'You must take responsibility for your actions.', 'B2', 'collocations'],
  ['draw a conclusion', 'делать вывод', 'It\'s too early to draw any conclusions.', 'B2', 'collocations'],
  ['run a business', 'управлять бизнесом', 'She runs her own business.', 'B2', 'collocations'],
  ['catch a cold', 'простудиться', 'I caught a cold last week.', 'B2', 'collocations'],
  ['break a promise', 'нарушить обещание', 'He broke his promise again.', 'B2', 'collocations'],
  ['keep in touch', 'поддерживать связь', 'Let\'s keep in touch by email.', 'B2', 'collocations'],

  // ===== TECH / CODING (B1-B2) — for developers =====
  ['deploy', 'развёртывать', 'We deploy the new version every Friday.', 'B2', 'tech'],
  ['framework', 'фреймворк', 'React is a popular JavaScript framework.', 'B2', 'tech'],
  ['backend', 'серверная часть', 'I work on the backend, she works on the frontend.', 'B2', 'tech'],
  ['frontend', 'клиентская часть', 'The frontend is built with React and Tailwind.', 'B2', 'tech'],
  ['database', 'база данных', 'All user data is stored in the database.', 'B1', 'tech'],
  ['query', 'запрос', 'This SQL query returns the top 10 customers.', 'B2', 'tech'],
  ['bug', 'баг/ошибка', 'I spent two hours fixing that bug.', 'B1', 'tech'],
  ['feature', 'функция', 'We added a new feature to the app.', 'B1', 'tech'],
  ['release', 'релиз/выпуск', 'The new release comes out next week.', 'B2', 'tech'],
  ['repository', 'репозиторий', 'Push your changes to the main repository.', 'B2', 'tech'],
  ['commit', 'коммит', 'Don\'t forget to commit your changes.', 'B2', 'tech'],
  ['merge', 'слияние', 'I need to merge this branch into main.', 'B2', 'tech'],
  ['branch', 'ветка', 'Create a new branch for this feature.', 'B2', 'tech'],
  ['pull request', 'пулл-реквест', 'Can you review my pull request?', 'B2', 'tech'],
  ['issue', 'проблема/тикет', 'I opened an issue about the login bug.', 'B1', 'tech'],
  ['debug', 'отлаживать', 'Let me debug this function.', 'B2', 'tech'],
  ['refactor', 'рефакторить', 'This code needs to be refactored.', 'B2', 'tech'],
  ['scalable', 'масштабируемый', 'We need a scalable architecture.', 'B2', 'tech'],
  ['endpoint', 'эндпоинт (API)', 'The API endpoint returns JSON.', 'B2', 'tech'],
  ['request', 'запрос', 'Send a GET request to this URL.', 'B1', 'tech'],
  ['response', 'ответ', 'The server returned a 200 response.', 'B1', 'tech'],
  ['payload', 'полезная нагрузка', 'Check the payload of the request.', 'B2', 'tech'],
  ['cache', 'кэш', 'Clear the cache and try again.', 'B1', 'tech'],
  ['latency', 'задержка', 'We reduced latency by 50%.', 'B2', 'tech'],
  ['throughput', 'пропускная способность', 'This server can handle higher throughput.', 'B2', 'tech'],
  ['client', 'клиент', 'The client needs to send an auth token.', 'B1', 'tech'],
  ['stack', 'стек технологий', 'Our stack is React, Node, and Postgres.', 'B2', 'tech'],
  ['schema', 'схема БД', 'We updated the database schema.', 'B2', 'tech'],
  ['authentication', 'аутентификация', 'User authentication is handled by JWT.', 'B2', 'tech'],
  ['authorization', 'авторизация', 'Authorization checks run on every request.', 'B2', 'tech'],
  ['dependency', 'зависимость', 'Install all dependencies first.', 'B2', 'tech'],
  ['environment', 'окружение', 'This only happens in the production environment.', 'B1', 'tech'],
  ['migration', 'миграция БД', 'Run the migration before deploying.', 'B2', 'tech'],
  ['rollback', 'откат', 'We had to rollback to the previous version.', 'B2', 'tech'],

  // ===== LINKING WORDS (writing connectors) =====
  ['however', 'однако', 'The plan is good. However, it needs more detail.', 'B1', 'linking words'],
  ['therefore', 'следовательно', 'It was raining; therefore, we stayed inside.', 'B1', 'linking words'],
  ['moreover', 'более того', 'The house is old. Moreover, the roof leaks.', 'B2', 'linking words'],
  ['furthermore', 'кроме того', 'The service is slow. Furthermore, it\'s expensive.', 'B2', 'linking words'],
  ['nevertheless', 'тем не менее', 'It was cold; nevertheless, we went swimming.', 'B2', 'linking words'],
  ['nonetheless', 'тем не менее', 'The task was hard. Nonetheless, she finished it.', 'B2', 'linking words'],
  ['on the other hand', 'с другой стороны', 'Cities are exciting. On the other hand, they\'re noisy.', 'B1', 'linking words'],
  ['in addition', 'в дополнение', 'In addition to English, she speaks French.', 'B1', 'linking words'],
  ['for instance', 'например', 'Many fruits are healthy. For instance, apples and bananas.', 'B1', 'linking words'],
  ['for example', 'например', 'Use linking words — for example, "however".', 'A2', 'linking words'],
  ['in contrast', 'в контраст', 'London is rainy. In contrast, Madrid is sunny.', 'B2', 'linking words'],
  ['consequently', 'в результате', 'He didn\'t study; consequently, he failed.', 'B2', 'linking words'],
  ['as a result', 'в результате', 'Prices went up. As a result, fewer people buy.', 'B1', 'linking words'],
  ['in fact', 'на самом деле', 'I thought it would be hard. In fact, it was easy.', 'B1', 'linking words'],
  ['indeed', 'действительно', 'The film was good — indeed, one of his best.', 'B2', 'linking words'],
  ['on the contrary', 'наоборот', 'He\'s not lazy. On the contrary, he works all day.', 'B2', 'linking words'],
  ['whereas', 'тогда как', 'I love coffee, whereas she prefers tea.', 'B2', 'linking words'],
  ['despite', 'несмотря на', 'Despite the rain, we had fun.', 'B1', 'linking words'],
  ['although', 'хотя', 'Although it was cold, we went out.', 'A2', 'linking words'],
  ['meanwhile', 'тем временем', 'I was cooking. Meanwhile, she was setting the table.', 'B1', 'linking words'],
  ['to sum up', 'подводя итог', 'To sum up, the project was successful.', 'B2', 'linking words'],
  ['in conclusion', 'в заключение', 'In conclusion, remote work has more benefits than costs.', 'B2', 'linking words'],
  ['first of all', 'прежде всего', 'First of all, let me introduce myself.', 'A2', 'linking words'],
  ['secondly', 'во-вторых', 'Secondly, we need to plan the budget.', 'B1', 'linking words'],
  ['finally', 'наконец', 'Finally, don\'t forget to save your work.', 'A2', 'linking words'],

  // ===== PHOTOGRAPHY / VIDEO =====
  ['aperture', 'диафрагма', 'A wide aperture blurs the background nicely.', 'B2', 'photography'],
  ['shutter speed', 'выдержка', 'Use a fast shutter speed to freeze motion.', 'B2', 'photography'],
  ['exposure', 'экспозиция', 'The exposure is too bright, lower it.', 'B2', 'photography'],
  ['lens', 'объектив', 'I bought a new 50mm lens last week.', 'B1', 'photography'],
  ['focal length', 'фокусное расстояние', 'A 35mm focal length is great for street photos.', 'B2', 'photography'],
  ['depth of field', 'глубина резкости', 'Shallow depth of field is perfect for portraits.', 'B2', 'photography'],
  ['composition', 'композиция', 'The composition of this photo is excellent.', 'B1', 'photography'],
  ['frame', 'кадр', 'Try to frame the subject in the center.', 'B1', 'photography'],
  ['crop', 'обрезать', 'I need to crop this image to 1:1.', 'B1', 'photography'],
  ['edit', 'редактировать', 'I edit all my photos in Lightroom.', 'A2', 'photography'],
  ['preset', 'пресет', 'This preset gives a warm cinematic look.', 'B2', 'photography'],
  ['tripod', 'штатив', 'Use a tripod for night photography.', 'B1', 'photography'],
  ['lighting', 'освещение', 'Good lighting is more important than the camera.', 'B1', 'photography'],
  ['shadow', 'тень', 'The shadows add depth to the shot.', 'A2', 'photography'],
  ['highlight', 'блик/светлое', 'Recover the highlights in post-processing.', 'B2', 'photography'],
  ['RAW file', 'RAW файл', 'Shoot in RAW for maximum editing flexibility.', 'B2', 'photography'],
  ['footage', 'отснятый материал', 'I have hours of footage to edit.', 'B2', 'photography'],
  ['clip', 'клип/фрагмент', 'Cut this clip at the 30-second mark.', 'B1', 'photography'],
  ['timeline', 'таймлайн', 'Drag the clip onto the timeline.', 'B1', 'photography'],
  ['transition', 'переход', 'A smooth transition between scenes.', 'B1', 'photography'],
  ['colour grading', 'цветокоррекция', 'Colour grading gives the video its mood.', 'B2', 'photography'],
  ['zoom', 'зум', 'Don\'t zoom too much, it looks amateur.', 'A2', 'photography'],
  ['pan', 'панорамирование', 'Pan the camera slowly to the left.', 'B2', 'photography'],
  ['stabilise', 'стабилизировать', 'Stabilise your shot with a gimbal.', 'B2', 'photography'],
  ['render', 'рендерить', 'The project will take 10 minutes to render.', 'B2', 'photography'],

  // ===== B2: ABSTRACT NOUNS & ANALYSIS (academic essentials) =====
  ['notion', 'понятие', 'I have no notion of what he meant.', 'B2', 'academic'],
  ['perception', 'восприятие', 'Public perception of the issue has shifted.', 'B2', 'academic'],
  ['assumption', 'допущение', 'That\'s a dangerous assumption to make.', 'B2', 'academic'],
  ['implication', 'последствие', 'The implications of this decision are huge.', 'B2', 'academic'],
  ['outcome', 'результат', 'The outcome was better than we hoped.', 'B2', 'academic'],
  ['discrepancy', 'расхождение', 'There\'s a discrepancy between the two reports.', 'C1', 'academic'],
  ['hypothesis', 'гипотеза', 'The data confirms our hypothesis.', 'B2', 'academic'],
  ['correlation', 'корреляция', 'There\'s a strong correlation between sleep and mood.', 'B2', 'academic'],
  ['paradigm', 'парадигма', 'A paradigm shift in how we treat the disease.', 'C1', 'academic'],
  ['premise', 'предпосылка', 'The argument is based on a flawed premise.', 'C1', 'academic'],
  ['rationale', 'обоснование', 'What\'s the rationale behind this rule?', 'C1', 'academic'],
  ['scope', 'охват', 'That\'s outside the scope of this study.', 'B2', 'academic'],
  ['scrutiny', 'проверка', 'Her work will not bear close scrutiny.', 'C1', 'academic'],
  ['threshold', 'порог', 'We\'ve reached the pain threshold.', 'B2', 'academic'],
  ['paradox', 'парадокс', 'It\'s a paradox: the more you sleep, the more tired you feel.', 'B2', 'academic'],
  ['phenomenon', 'явление', 'Climate change is a global phenomenon.', 'B2', 'academic'],
  ['consensus', 'консенсус', 'There is broad scientific consensus on this.', 'B2', 'academic'],
  ['contradiction', 'противоречие', 'His actions are in direct contradiction to his words.', 'B2', 'academic'],
  ['ambiguity', 'неоднозначность', 'The contract has too much ambiguity.', 'C1', 'academic'],
  ['nuance', 'нюанс', 'There is a subtle nuance in his argument.', 'C1', 'academic'],

  // ===== B2-C1: BUSINESS & WORK =====
  ['leverage', 'использовать', 'We can leverage our experience to win the deal.', 'C1', 'work'],
  ['stakeholder', 'заинтересованная сторона', 'All stakeholders must agree before we proceed.', 'B2', 'work'],
  ['streamline', 'оптимизировать', 'We need to streamline the process.', 'B2', 'work'],
  ['feasible', 'осуществимый', 'Is the project feasible within the budget?', 'B2', 'work'],
  ['lucrative', 'прибыльный', 'It turned out to be a lucrative business.', 'C1', 'work'],
  ['endeavour', 'начинание', 'Wishing you success in your new endeavour.', 'C1', 'work'],
  ['undertake', 'предпринимать', 'They will undertake a thorough investigation.', 'B2', 'work'],
  ['pursue', 'преследовать', 'She decided to pursue a career in law.', 'B2', 'work'],
  ['delegate', 'делегировать', 'A good manager knows when to delegate.', 'B2', 'work'],
  ['mitigate', 'смягчать', 'Steps to mitigate the financial risks.', 'C1', 'work'],
  ['comprehensive', 'всеобъемлющий', 'We need a comprehensive review of the policy.', 'B2', 'work'],
  ['scrutinise', 'тщательно изучать', 'Investors will scrutinise the financials.', 'C1', 'work'],
  ['allocate', 'распределять', 'How should we allocate the budget?', 'B2', 'work'],
  ['expenditure', 'расходы', 'Public expenditure on health has risen.', 'C1', 'work'],
  ['negotiate', 'вести переговоры', 'We managed to negotiate a better price.', 'B2', 'work'],
  ['compromise', 'компромисс', 'Both sides had to make a compromise.', 'B2', 'work'],
  ['bottleneck', 'узкое место', 'Approval is the main bottleneck in our workflow.', 'C1', 'work'],
  ['outsource', 'передавать на аутсорс', 'The company outsources its IT support.', 'B2', 'work'],
  ['breakthrough', 'прорыв', 'A scientific breakthrough in cancer treatment.', 'B2', 'work'],
  ['plummet', 'резко падать', 'Sales plummeted after the bad review.', 'C1', 'work'],

  // ===== B2-C1: DESCRIBING TRENDS & CHANGE (IELTS / academic writing) =====
  ['surge', 'резкий рост', 'A surge in demand caught the company off guard.', 'B2', 'trends'],
  ['plummet', 'резко падать', 'Profits plummeted in the third quarter.', 'C1', 'trends'],
  ['fluctuate', 'колебаться', 'Prices fluctuate with the season.', 'B2', 'trends'],
  ['steady', 'стабильный', 'There has been a steady increase in users.', 'B1', 'trends'],
  ['gradual', 'постепенный', 'A gradual decline in attendance over the years.', 'B2', 'trends'],
  ['dramatic', 'резкий', 'A dramatic rise in fuel prices.', 'B2', 'trends'],
  ['marginal', 'незначительный', 'Only a marginal improvement was observed.', 'C1', 'trends'],
  ['substantial', 'значительный', 'A substantial drop in unemployment.', 'B2', 'trends'],
  ['negligible', 'ничтожный', 'The difference is negligible.', 'C1', 'trends'],
  ['peak', 'достигать пика', 'Sales peaked in December.', 'B2', 'trends'],
  ['plateau', 'выходить на плато', 'Growth has plateaued in recent months.', 'C1', 'trends'],
  ['outpace', 'опережать', 'Demand has outpaced supply.', 'C1', 'trends'],
  ['lag behind', 'отставать', 'Our sales lag behind those of competitors.', 'B2', 'trends'],
  ['accelerate', 'ускорять(ся)', 'The pace of change is accelerating.', 'B2', 'trends'],
  ['stagnate', 'стагнировать', 'The economy has stagnated for two years.', 'C1', 'trends'],
  ['rebound', 'восстанавливаться', 'The market rebounded sharply.', 'C1', 'trends'],
  ['halve', 'уменьшить вдвое', 'The company aims to halve its emissions.', 'B2', 'trends'],
  ['double', 'удваивать(ся)', 'Sales have doubled in the last decade.', 'B1', 'trends'],
  ['triple', 'утраивать(ся)', 'The population tripled in fifty years.', 'B2', 'trends'],
  ['skyrocket', 'взлететь', 'Housing prices have skyrocketed.', 'C1', 'trends'],

  // ===== B2-C1: ENVIRONMENT & SCIENCE =====
  ['sustainable', 'устойчивый', 'We need a sustainable energy policy.', 'B2', 'environment'],
  ['emission', 'выброс', 'Carbon emissions must be reduced.', 'B2', 'environment'],
  ['biodiversity', 'биоразнообразие', 'Tropical forests have rich biodiversity.', 'C1', 'environment'],
  ['ecosystem', 'экосистема', 'The reef is a delicate ecosystem.', 'B2', 'environment'],
  ['habitat', 'среда обитания', 'Pandas\' natural habitat is shrinking.', 'B2', 'environment'],
  ['extinction', 'вымирание', 'Many species are on the brink of extinction.', 'B2', 'environment'],
  ['conservation', 'охрана природы', 'Wildlife conservation is a priority.', 'B2', 'environment'],
  ['pollutant', 'загрязнитель', 'The river contains several pollutants.', 'C1', 'environment'],
  ['renewable', 'возобновляемый', 'Solar energy is renewable.', 'B2', 'environment'],
  ['fossil fuel', 'ископаемое топливо', 'Coal is a fossil fuel.', 'B2', 'environment'],
  ['climate', 'климат', 'The climate is changing rapidly.', 'B1', 'environment'],
  ['drought', 'засуха', 'The region is suffering from a severe drought.', 'B2', 'environment'],
  ['flood', 'наводнение', 'Heavy rain caused a flash flood.', 'B1', 'environment'],
  ['deforestation', 'вырубка лесов', 'Deforestation is destroying habitats.', 'C1', 'environment'],
  ['greenhouse', 'парниковый', 'Greenhouse gases trap heat in the atmosphere.', 'B2', 'environment'],
  ['carbon footprint', 'углеродный след', 'Reduce your carbon footprint by walking.', 'B2', 'environment'],
  ['recycling', 'переработка', 'Recycling helps reduce waste.', 'B1', 'environment'],
  ['biodegradable', 'биоразлагаемый', 'These bags are biodegradable.', 'C1', 'environment'],
  ['ozone', 'озон', 'The ozone layer protects us from UV radiation.', 'B2', 'environment'],
  ['pristine', 'нетронутый', 'Pristine wilderness is rare these days.', 'C1', 'environment'],

  // ===== B2-C1: SOCIETY & POLITICS =====
  ['inequality', 'неравенство', 'Income inequality is a serious issue.', 'B2', 'society'],
  ['discrimination', 'дискриминация', 'Discrimination based on race is illegal.', 'B2', 'society'],
  ['poverty', 'бедность', 'Millions live in extreme poverty.', 'B1', 'society'],
  ['immigration', 'иммиграция', 'Immigration policy is hotly debated.', 'B2', 'society'],
  ['legislation', 'законодательство', 'New legislation will tighten data protection.', 'C1', 'society'],
  ['advocate', 'защитник / выступать за', 'She advocates for women\'s rights.', 'B2', 'society'],
  ['controversial', 'спорный', 'It\'s a controversial decision.', 'B2', 'society'],
  ['referendum', 'референдум', 'A referendum will decide the issue.', 'C1', 'society'],
  ['pundit', 'эксперт', 'Political pundits debated all night.', 'C1', 'society'],
  ['constituency', 'избирательный округ', 'She represents a rural constituency.', 'C1', 'society'],
  ['turnout', 'явка', 'Voter turnout was unexpectedly high.', 'B2', 'society'],
  ['regime', 'режим', 'The new regime promised reform.', 'B2', 'society'],
  ['demonstration', 'демонстрация', 'A peaceful demonstration was held.', 'B2', 'society'],
  ['polarise', 'поляризовать', 'The issue has polarised the country.', 'C1', 'society'],
  ['rhetoric', 'риторика', 'His rhetoric is more impressive than his policies.', 'C1', 'society'],
  ['scrutiny', 'проверка', 'The minister came under intense scrutiny.', 'C1', 'society'],
  ['integrity', 'честность', 'A leader of great integrity.', 'B2', 'society'],
  ['transparent', 'прозрачный', 'We need a transparent government.', 'B2', 'society'],
  ['accountability', 'подотчётность', 'There must be accountability for these decisions.', 'C1', 'society'],
  ['exempt', 'освобождённый', 'Charities are exempt from this tax.', 'C1', 'society'],

  // ===== C1: ADVANCED ADJECTIVES (CAE/CPE) =====
  ['compelling', 'убедительный', 'She presented a compelling argument.', 'C1', 'descriptive'],
  ['profound', 'глубокий', 'The book had a profound effect on me.', 'C1', 'descriptive'],
  ['inevitable', 'неизбежный', 'Some changes are inevitable.', 'B2', 'descriptive'],
  ['arbitrary', 'произвольный', 'The decision seems arbitrary.', 'C1', 'descriptive'],
  ['ambiguous', 'двусмысленный', 'The instructions are ambiguous.', 'C1', 'descriptive'],
  ['coherent', 'связный', 'A coherent strategy is needed.', 'B2', 'descriptive'],
  ['intricate', 'запутанный', 'The plot is incredibly intricate.', 'C1', 'descriptive'],
  ['subtle', 'тонкий', 'There\'s a subtle difference between them.', 'B2', 'descriptive'],
  ['versatile', 'универсальный', 'She is a versatile actress.', 'B2', 'descriptive'],
  ['inherent', 'присущий', 'Risk is inherent in any investment.', 'C1', 'descriptive'],
  ['plausible', 'правдоподобный', 'It\'s a plausible explanation.', 'C1', 'descriptive'],
  ['superficial', 'поверхностный', 'His knowledge is superficial.', 'C1', 'descriptive'],
  ['meticulous', 'дотошный', 'A meticulous attention to detail.', 'C1', 'descriptive'],
  ['ubiquitous', 'вездесущий', 'Smartphones are now ubiquitous.', 'C1', 'descriptive'],
  ['tedious', 'утомительный', 'The journey was tedious.', 'B2', 'descriptive'],
  ['mundane', 'обыденный', 'Mundane tasks fill the day.', 'C1', 'descriptive'],
  ['exquisite', 'изысканный', 'An exquisite piece of jewellery.', 'C1', 'descriptive'],
  ['lavish', 'роскошный', 'A lavish wedding reception.', 'C1', 'descriptive'],
  ['scarce', 'дефицитный', 'Water is scarce in the desert.', 'B2', 'descriptive'],
  ['abundant', 'обильный', 'The region is rich in abundant wildlife.', 'B2', 'descriptive'],

  // ===== C1: ADVANCED VERBS =====
  ['attribute', 'приписывать', 'The success is attributed to teamwork.', 'B2', 'verbs'],
  ['highlight', 'подчёркивать', 'The report highlights several issues.', 'B2', 'verbs'],
  ['illustrate', 'иллюстрировать', 'This case illustrates the problem perfectly.', 'B2', 'verbs'],
  ['undermine', 'подрывать', 'Constant criticism can undermine confidence.', 'C1', 'verbs'],
  ['reinforce', 'укреплять', 'These results reinforce our hypothesis.', 'B2', 'verbs'],
  ['compile', 'составлять', 'They compiled a list of names.', 'B2', 'verbs'],
  ['exemplify', 'служить примером', 'Her work exemplifies modern design.', 'C1', 'verbs'],
  ['endure', 'выдерживать', 'The bridge has endured for centuries.', 'C1', 'verbs'],
  ['exacerbate', 'усугублять', 'The new rules exacerbate the problem.', 'C1', 'verbs'],
  ['elicit', 'вызывать', 'The question elicited an angry response.', 'C1', 'verbs'],
  ['discern', 'различать', 'It\'s hard to discern the truth here.', 'C1', 'verbs'],
  ['contemplate', 'обдумывать', 'She is contemplating a career change.', 'B2', 'verbs'],
  ['speculate', 'предполагать', 'Analysts speculate that prices will fall.', 'B2', 'verbs'],
  ['endorse', 'поддерживать', 'Several MPs have endorsed the plan.', 'C1', 'verbs'],
  ['refrain', 'воздерживаться', 'Please refrain from smoking.', 'C1', 'verbs'],
  ['retain', 'сохранять', 'The town has retained its old charm.', 'B2', 'verbs'],
  ['relinquish', 'отказываться', 'He had to relinquish control of the company.', 'C1', 'verbs'],
  ['intervene', 'вмешиваться', 'Police had to intervene in the dispute.', 'B2', 'verbs'],
  ['coincide', 'совпадать', 'My birthday coincides with the conference.', 'B2', 'verbs'],
  ['anticipate', 'предвидеть', 'We anticipated the problem in advance.', 'B2', 'verbs'],

  // ===== B2-C1: COLLOCATIONS (high-frequency in CAE/IELTS) =====
  ['take into account', 'учитывать', 'We must take into account all the costs.', 'B2', 'collocations'],
  ['draw a conclusion', 'делать вывод', 'It\'s too early to draw a conclusion.', 'B2', 'collocations'],
  ['raise awareness', 'повышать осведомлённость', 'The campaign aims to raise awareness.', 'B2', 'collocations'],
  ['set a precedent', 'создавать прецедент', 'The ruling could set a precedent.', 'C1', 'collocations'],
  ['bear in mind', 'помнить', 'Bear in mind that prices may change.', 'B2', 'collocations'],
  ['take a stance', 'занять позицию', 'The company took a strong stance on the issue.', 'C1', 'collocations'],
  ['strike a balance', 'найти баланс', 'We must strike a balance between work and rest.', 'B2', 'collocations'],
  ['reach a consensus', 'достичь согласия', 'The committee reached a consensus.', 'B2', 'collocations'],
  ['gain insight', 'получить понимание', 'The research gives us insight into the problem.', 'B2', 'collocations'],
  ['pose a threat', 'представлять угрозу', 'Climate change poses a threat to coastal cities.', 'B2', 'collocations'],
  ['have a knack for', 'иметь способность', 'She has a knack for languages.', 'C1', 'collocations'],
  ['come to terms with', 'смириться с', 'He had to come to terms with the loss.', 'C1', 'collocations'],
  ['take its toll', 'сказываться', 'The years of stress have taken their toll.', 'C1', 'collocations'],
  ['shed light on', 'пролить свет на', 'The findings shed light on the mystery.', 'C1', 'collocations'],
  ['pave the way', 'проложить путь', 'This discovery paves the way for new treatments.', 'C1', 'collocations'],
  ['put forward', 'выдвигать', 'She put forward a controversial proposal.', 'B2', 'collocations'],
  ['back up', 'подтверждать', 'You need data to back up your claim.', 'B2', 'collocations'],
  ['carry weight', 'иметь вес', 'His opinion carries a lot of weight here.', 'C1', 'collocations'],
  ['narrow the gap', 'сократить разрыв', 'New policies aim to narrow the wealth gap.', 'B2', 'collocations'],
  ['rule out', 'исключать', 'Doctors have ruled out a heart attack.', 'B2', 'collocations'],
]

export const vocabularySeed: VocabSeed[] = rows.map(([word, translation, example, cefrLevel, topic]) => ({
  word,
  translation,
  example,
  cefrLevel,
  topic,
}))
